### ISSUE TITLE
模型训练和推理的时候爆显存

### ISSUE THREAD

**Issue by Nomination-NRB** [modelscope/facechain#105]
你好，我使用的是**NVIDIA 3090 24G**显存的，在训练和推理的过程中存在爆显存导致推理失败的情况，请问是否有方法调整配置信息或者批量大小等其他参数来降低爆显存的概率呢，因为现在运行此项目的时候**有时候可以正常**出图，但有时候会失败。

最开始的时候训练都可能爆显存，然后我设置了**export PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:256**
在这之后训练过程没问题了，但是推理的时候会失败

报错日志：
2023-08-24 09:18:22,326 - modelscope - INFO - load facefusion models done
2023-08-24 09:18:22,328 - modelscope - INFO - init done
2023-08-24 09:18:22,345 - modelscope - WARNING - No preprocessor field found in cfg.
2023-08-24 09:18:22,345 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-08-24 09:18:22,345 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/home/hx/.cache/modelscope/hub/damo/cv_unet-image-face-fusion_damo'}. trying to build by task and model information.
2023-08-24 09:18:22,345 - modelscope - WARNING - No preprocessor key ('image-face-fusion', 'image-face-fusion') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-08-24 09:18:22,346 - modelscope - INFO - image face fusion model init done
2023-08-24 09:18:22,365 - modelscope - WARNING - task image-face-fusion input definition is missing
2023-08-24 09:18:22.626739: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 4.74G (5088778496 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.627710: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 4.26G (4579900416 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.628641: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 3.84G (4121910272 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.629580: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 3.45G (3709719040 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.630524: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 3.11G (3338747136 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.631429: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 2.80G (3004872448 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.632331: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 2.52G (2704385024 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.633273: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 2.27G (2433946368 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.634196: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 2.04G (2190551552 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.635080: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 1.84G (1971496448 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.635995: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 1.65G (1774346752 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.636931: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 1.49G (1596912128 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.637843: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 1.34G (1437220864 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.638732: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 1.20G (1293498880 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.639605: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 1.08G (1164148992 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.640496: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 999.20M (1047734272 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.641442: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 899.28M (942960896 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.642358: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 809.35M (848664832 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.643280: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 728.42M (763798528 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.644190: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 655.57M (687418880 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-08-24 09:18:22.660534: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8400
/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/modelscope/models/cv/image_face_fusion/facelib/matlab_cp2tform.py:81: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  r, _, _, _ = lstsq(X, U)
/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/functional.py:4227: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
Traceback (most recent call last):
  File "run_inference.py", line 50, in <module>
    outputs = gen_portrait(processed_dir, num_generate, base_model,
  File "/home/hx/facechain/facechain/inference.py", line 221, in __call__
    swap_results = face_swap_fn(self.use_face_swap, gen_results, selected_face)
  File "/home/hx/facechain/facechain/inference.py", line 150, in face_swap_fn
    result = image_face_fusion(dict(template=img, user=template_face))[OutputKeys.OUTPUT_IMG]
  File "/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 219, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 254, in _process_single
    out = self.forward(out, **forward_params)
  File "/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/modelscope/pipelines/cv/image_face_fusion_pipeline.py", line 62, in forward
    output = self.model.inference(template_img, user_img)
  File "/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/modelscope/models/cv/image_face_fusion/image_face_fusion.py", line 242, in inference
    Yt_trans_inv = warp_affine_torch(Yt, trans_inv, (ori_h, ori_w))
  File "/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/modelscope/models/cv/image_face_fusion/network/ops.py", line 201, in warp_affine_torch
    dst_norm_trans_src_norm = normalize_homography(M_3x3, (H, W), dsize)
  File "/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/modelscope/models/cv/image_face_fusion/network/ops.py", line 166, in normalize_homography
    src_pix_trans_src_norm = _torch_inverse_cast(src_norm_trans_src_pix)
  File "/home/hx/anaconda3/envs/facechain/lib/python3.8/site-packages/modelscope/models/cv/image_face_fusion/network/ops.py", line 143, in _torch_inverse_cast
    return torch.inverse(input.to(dtype)).to(input.dtype)
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

**Comment by tastelikefeet** [comment]
您使用的代码有修改吗？我们使用22G显存并没有发生爆显存的情况

**Comment by Nomination-NRB** [comment]
> 您使用的代码有修改吗？我们使用22G显存并没有发生爆显存的情况

您好，代码没有修改过，我尝试使用webui运行和直接 脚本 运行都存在爆显存的情况(不稳定，有些时候正常，有些时候失败)，而且GPU基本没有其他任务在消耗资源
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:17:00.0 Off |                  N/A |
| 80%   88C    P2   319W / 350W |  19490MiB / 24576MiB |     96%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:65:00.0  On |                  N/A |
| 34%   51C    P8    38W / 350W |    499MiB / 24576MiB |     15%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
