### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by Aruen24** [modelscope/facechain#13]
run the script  PYTHONPATH=. sh train_lora.sh "ly261666/cv_portrait_model" "v2.0" "film/film" "./imgs" "./processed" "./output"

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 399410) of binary: /home/disk01/wyw/.conda/envs/facechain/bin/python
Traceback (most recent call last):
  File "/home/disk01/wyw/.conda/envs/facechain/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/disk01/wyw/.conda/envs/facechain/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/disk01/wyw/.conda/envs/facechain/lib/python3.8/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/home/disk01/wyw/.conda/envs/facechain/lib/python3.8/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/disk01/wyw/.conda/envs/facechain/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/disk01/wyw/.conda/envs/facechain/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/disk01/wyw/.conda/envs/facechain/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
facechain/train_text_to_image_lora.py FAILED

**Comment by p21nc3** [comment]
@Aruen24 possibly this error this thrown due to memory outage or OS resource shortage, still need some more clarity on this. Kindly provide the steps to reproduce the same error. Also drop your system state/version/OS while running facechain.

**Comment by Aruen24** [comment]
single gpu run can solve the problem

**Comment by Kristin279** [comment]
Can't get rid of the torturer error...not my kid...they all want automation over this error

**Comment by Kristin279** [comment]
> single gpu run can solve the problem

**Comment by shengzewen** [comment]
> > 单GPU运行即可解决问题

请问在哪个地方设置单个GPU

**Comment by sunbaigui** [comment]
we will release the new doc soon to solve multiple gpu problem

**Comment by yingdachen** [comment]
> > > 单GPU运行即可解决问题
> 
> 请问在哪个地方设置单个GPU

check the latest readme

 CUDA_VISIBLE_DEVICES=0 python3 app.py
