### ISSUE TITLE
KeyError: 'vision_model.vision_model.embeddings.position_ids'

### ISSUE THREAD

**Issue by luoxianjun** [modelscope/facechain#139]
KeyError: 'vision_model.vision_model.embeddings.position_ids'

**Comment by sunbaigui** [comment]
please post the screen shot of env and log.

**Comment by huan-xi** [comment]
使用艺术照报这个错误

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/huanxi/facechain_new/facechain/inference_inpaint.py", line 219, in __call__
    generate_image_old = sd_inpaint_pipeline(
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py", line 1333, in __call__
    image, has_nsfw_concept = self.run_safety_checker(image, device, prompt_embeds.dtype)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py", line 550, in run_safety_checker
    image, has_nsfw_concept = self.safety_checker(
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/safety_checker.py", line 51, in forward
    pooled_output = self.vision_model(clip_input)[1]  # pooled_output
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 941, in forward
    return self.vision_model(
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 866, in forward
    hidden_states = self.embeddings(pixel_values)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/hooks.py", line 287, in pre_forward
    module, name, self.execution_device, value=self.weights_map[name], fp16_statistics=fp16_statistics
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/utils/offload.py", line 119, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
KeyError: 'vision_model.vision_model.embeddings.position_ids'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 349, in async_iteration
    return await iterator.__anext__()
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 342, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 325, in run_sync_iterator_async
    return next(iterator)
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 694, in gen_wrapper
    yield from f(*args, **kwargs)
  File "app.py", line 274, in launch_pipeline_inpaint
    outputs = future.result()
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
KeyError: 'vision_model.vision_model.embeddings.position_ids'

**Comment by sunbaigui** [comment]
> 使用艺术照报这个错误
> 
> concurrent.futures.process._RemoteTraceback: """ Traceback (most recent call last): File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker r = call_item.fn(*call_item.args, **call_item.kwargs) File "/home/huanxi/facechain_new/facechain/inference_inpaint.py", line 219, in **call** generate_image_old = sd_inpaint_pipeline( File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py", line 1333, in **call** image, has_nsfw_concept = self.run_safety_checker(image, device, prompt_embeds.dtype) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py", line 550, in run_safety_checker image, has_nsfw_concept = self.safety_checker( File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward output = old_forward(*args, **kwargs) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/safety_checker.py", line 51, in forward pooled_output = self.vision_model(clip_input)[1] # pooled_output File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 941, in forward return self.vision_model( File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 866, in forward hidden_states = self.embeddings(pixel_values) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/hooks.py", line 160, in new_forward args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/hooks.py", line 287, in pre_forward module, name, self.execution_device, value=self.weights_map[name], fp16_statistics=fp16_statistics File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/utils/offload.py", line 119, in **getitem** return self.dataset[f"{self.prefix}{key}"] KeyError: 'vision_model.vision_model.embeddings.position_ids' """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict output = await app.get_blocks().process_api( File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/blocks.py", line 1431, in process_api result = await self.call_function( File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/blocks.py", line 1123, in call_function prediction = await utils.async_iteration(iterator) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 349, in async_iteration return await iterator.**anext**() File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 342, in **anext** return await anyio.to_thread.run_sync( File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 325, in run_sync_iterator_async return next(iterator) File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 694, in gen_wrapper yield from f(*args, **kwargs) File "app.py", line 274, in launch_pipeline_inpaint outputs = future.result() File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/concurrent/futures/_base.py", line 437, in result return self.__get_result() File "/home/huanxi/anaconda3/envs/facechain/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result raise self._exception KeyError: 'vision_model.vision_model.embeddings.position_ids'

@wuziheng @bubbliiiing once you have time, please check on this  issue.

**Comment by wuziheng** [comment]
我来测试一下。

**Comment by wuziheng** [comment]
@huan-xi  我在本地没有复现这一问题，但我查看了相关代码 请到facechain/inference_inpaint.py 修改L56~60 
    pipeline = StableDiffusionControlNetInpaintPipeline.from_pretrained(
        baseline_model_path,
        controlnet=controlnet,
        torch_dtype=weight_dtype,
    ).to("cuda")
   改成
    pipeline = StableDiffusionControlNetInpaintPipeline.from_pretrained(
        baseline_model_path,
        safety_checker=None, 
        controlnet=controlnet,
        torch_dtype=weight_dtype,
    ).to("cuda")  试试，如果这样work，我们会发布一个修复，但这样会禁用safety_checker

**Comment by wuziheng** [comment]
@huan-xi  并请麻烦也测一下 inference.py 对应的形象生成，是否存在这一问题，帮助我们可以更好的定位，为什么艺术照功能会出现这一问题。

**Comment by wuziheng** [comment]
然后我简单提供一下我的环境，方便大家找到问题
![截屏2023-08-30 上午11 16 06](https://github.com/modelscope/facechain/assets/11889926/171a8c1e-5552-47ae-97c2-ccd571a2e25d)

**Comment by huan-xi** [comment]
> @huan-xi 我在本地没有复现这一问题，但我查看了相关代码 请到facechain/inference_inpaint.py 修改L56~60 pipeline = StableDiffusionControlNetInpaintPipeline.from_pretrained( baseline_model_path, controlnet=controlnet, torch_dtype=weight_dtype, ).to("cuda") 改成 pipeline = StableDiffusionControlNetInpaintPipeline.from_pretrained( baseline_model_path, safety_checker=None, controlnet=controlnet, torch_dtype=weight_dtype, ).to("cuda") 试试，如果这样work，我们会发布一个修复，但这样会禁用safety_checker

改完之后可以正常出图
