### ISSUE TITLE
ubuntu 22.04 本地搭建环境，点击开始训练报错

### ISSUE THREAD

**Issue by 2016geek** [modelscope/facechain#140]
cuda版本12.2
pytorch 使用pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 安装
可视化界面可以启动成功，但是点击开始训练按钮，后台安装完模型后报错
报错信息如下
Process Process-1:
Traceback (most recent call last):
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leon/facechain/facechain/inference.py", line 24, in _data_process_fn_process
    Blipv2()(input_img_dir)
  File "/home/leon/facechain/facechain/data_process/preprocessing.py", line 315, in __init__
    self.skin_retouching = pipeline(Tasks.skin_retouching, model='damo/cv_unet_skin-retouching', model_revision='v1.0.0')
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 147, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 59, in build_pipeline
    return build_from_cfg(
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/modelscope/utils/registry.py", line 184, in build_from_cfg
    LazyImportModule.import_module(sig)
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 458, in import_module
    requires(module_name, requirements)
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 337, in requires
    raise ImportError(''.join(failed))
ImportError: 
modelscope.pipelines.cv.skin_retouching_pipeline requires the TensorFlow library but it was not found in your environment. Checkout the instructions on the
installation page: https://www.tensorflow.org/install and follow the ones that match your environment.

instance_data_dir /tmp/qw/training_data/personalization_lora
Traceback (most recent call last):
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/leon/anaconda3/envs/facechain/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/leon/facechain/app.py", line 336, in run
    train_lora_fn(foundation_model_path='ly261666/cv_portrait_model',
  File "/home/leon/facechain/app.py", line 81, in train_lora_fn
    validation_prompt, _ = get_popular_prompts(output_img_dir)
  File "/home/leon/facechain/facechain/data_process/preprocessing.py", line 26, in get_popular_prompts
    f = open(os.path.join(train_dir, 'metadata.jsonl'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qw/training_data/personalization_lora_labeled/metadata.jsonl'

希望告知如何解决，感谢！

**Comment by ultimatech-cn** [comment]
是这段错误信息：
ImportError:
modelscope.pipelines.cv.skin_retouching_pipeline requires the TensorFlow library but it was not found in your environment. Checkout the instructions on the
installation page: https://www.tensorflow.org/install and follow the ones that match your environment.

要卸载torch，再安装cuba版本的。

**Comment by sunbaigui** [comment]
<img width="834" alt="image" src="https://github.com/modelscope/facechain/assets/2352602/e65e4d66-fcb4-47fc-918f-4116d77868f0">
this is the key issue, please try @ultimatech-cn 's solution. he's professional at these problems. Besides we'll work on replace tensorflow with pytorch for unify and clean env this week.
