### ISSUE TITLE
win10可以运行吗？

### ISSUE THREAD

**Issue by 00wan00** [modelscope/facechain#150]
我的是win10系统，把所有的依赖都按好了。提示以下错误，是不是win10不能运行这个项目啊？
Traceback (most recent call last):
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\utils\registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\models\base\base_model.py", line 66, in _instantiate
    return cls(**kwargs)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\models\cv\face_detection\scrfd\damofd_detect.py", line 31, in __init__
    super().__init__(model_dir, **kwargs)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\models\cv\face_detection\scrfd\scrfd_detect.py", line 33, in __init__
    from mmcv import Config
ImportError: cannot import name 'Config' from 'mmcv' (D:\facechain-main\facechain-main\venv\lib\site-packages\mmcv\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\pipelines\cv\face_detection_pipeline.py", line 36, in __init__
    super().__init__(model=model, **kwargs)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\pipelines\base.py", line 99, in __init__
    self.model = self.initiate_single_model(model)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\models\base\base_model.py", line 151, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: DamoFdDetect: cannot import name 'Config' from 'mmcv' (D:\facechain-main\facechain-main\venv\lib\site-packages\mmcv\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\facechain-main\facechain-main\facechain\inference.py", line 24, in _data_process_fn_process
    Blipv2()(input_img_dir)
  File "D:\facechain-main\facechain-main\facechain\data_process\preprocessing.py", line 316, in __init__
    self.face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_ddsar_face-detection_iclr23-damofd', model_revision='v1.1')
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\pipelines\builder.py", line 147, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\pipelines\builder.py", line 59, in build_pipeline
    return build_from_cfg(
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: FaceDetectionPipeline: DamoFdDetect: cannot import name 'Config' from 'mmcv' (D:\facechain-main\facechain-main\venv\lib\site-packages\mmcv\__init__.py)
instance_data_dir /tmp\qw\training_data\personalization_lora
Traceback (most recent call last):
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\facechain-main\facechain-main\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\facechain-main\facechain-main\app.py", line 336, in run
    train_lora_fn(foundation_model_path='ly261666/cv_portrait_model',
  File "D:\facechain-main\facechain-main\app.py", line 81, in train_lora_fn
    validation_prompt, _ = get_popular_prompts(output_img_dir)
  File "D:\facechain-main\facechain-main\facechain\data_process\preprocessing.py", line 26, in get_popular_prompts
    f = open(os.path.join(train_dir, 'metadata.jsonl'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp\\qw\\training_data\\personalization_lora_labeled\\metadata.jsonl'

**Comment by ultimatech-cn** [comment]
windows肯定可以运行，请参考https://zhuanlan.zhihu.com/p/651180440
你在windows上运行，需要修改app.py

**Comment by sunbaigui** [comment]
> windows肯定可以运行，请参考https://zhuanlan.zhihu.com/p/651180440 你在windows上运行，需要修改app.py

try this, if you have any further issues, feel free to reopen it.
