### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qw/training_data/ly261666/cv_portrait_model/test_labeled/metadata.jsonl'

### ISSUE THREAD

**Issue by whiteewei** [modelscope/facechain#166]
Always got file not found error while training Lora in colab at both models.
Log:

/content/facechain
2023-09-02 05:10:01,230 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-02 05:10:01,232 - modelscope - INFO - TensorFlow version 2.12.0 Found.
2023-09-02 05:10:01,232 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-09-02 05:10:01,232 - modelscope - INFO - No valid ast index found from /root/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2023-09-02 05:10:01,285 - modelscope - INFO - Loading done! Current index file version is 1.8.4, with md5 51a048dace3a110560e1ffb667782db4 and a total number of 902 components indexed
2023-09-02 05:10:02.852720: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-02 05:10:02.910942: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-02 05:10:03.950787: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/content/facechain/app.py:659: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
/content/facechain/app.py:706: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  gallery = gr.Gallery(template_gallery_list).style(grid=4, height=300)
/content/facechain/app.py:706: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  gallery = gr.Gallery(template_gallery_list).style(grid=4, height=300)
/content/facechain/app.py:757: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://6613a1561310d6d905.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
--------uuid:  qw
----------work_dir:  /tmp/qw/YorickHe/majicmixRealistic_v6/test
2023-09-02 05:12:57,754 - modelscope - INFO - Use user-specified model revision: v1.0.0
Downloading: 100% 721/721 [00:00<00:00, 3.51MB/s]
Downloading: 100% 42.6M/42.6M [00:02<00:00, 18.6MB/s]
2023-09-02 05:13:01,840 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:13:02,623 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:13:03,498 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:13:04,254 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:13:04,913 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:13:08,946 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-02 05:13:08,949 - modelscope - INFO - TensorFlow version 2.12.0 Found.
2023-09-02 05:13:08,949 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-09-02 05:13:08,984 - modelscope - INFO - Loading done! Current index file version is 1.8.4, with md5 51a048dace3a110560e1ffb667782db4 and a total number of 902 components indexed
2023-09-02 05:13:11.007986: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/content/facechain/app.py:659: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
/content/facechain/app.py:706: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  gallery = gr.Gallery(template_gallery_list).style(grid=4, height=300)
/content/facechain/app.py:706: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  gallery = gr.Gallery(template_gallery_list).style(grid=4, height=300)
/content/facechain/app.py:757: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
2023-09-02 05:13:16,324 - modelscope - INFO - Use user-specified model revision: v4.0
Downloading: 100% 577/577 [00:00<00:00, 3.20MB/s]
Downloading: 100% 560/560 [00:00<00:00, 3.73MB/s]
Downloading: 100% 4.78k/4.78k [00:00<00:00, 767kB/s]
Downloading: 100% 1.64k/1.64k [00:00<00:00, 10.5MB/s]
Downloading: 100% 4.78k/4.78k [00:00<00:00, 1.18MB/s]
Downloading: 100% 577/577 [00:00<00:00, 3.79MB/s]
Downloading: 100% 1.64k/1.64k [00:00<00:00, 10.3MB/s]
Downloading: 100% 560/560 [00:00<00:00, 3.62MB/s]
Downloading:  91% 2.92G/3.20G [01:27<00:17, 17.3MB/s]Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 814, in _raw_read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 799, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.10/http/client.py", line 466, in read
    s = self.fp.read(amt)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 940, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 879, in read
    data = self._raw_read(amt)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 813, in _raw_read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 715, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='[www.modelscope.cn](http://www.modelscope.cn/)', port=80): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/facechain/facechain/inference.py", line 24, in _data_process_fn_process
    Blipv2()(input_img_dir)
  File "/content/facechain/facechain/data_process/preprocessing.py", line 314, in __init__
    self.model = DeepDanbooru()
  File "/content/facechain/facechain/data_process/deepbooru.py", line 721, in __init__
    snapshot_path = snapshot_download(foundation_model_id, revision='v4.0')
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/snapshot_download.py", line 140, in snapshot_download
    parallel_download(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/file_download.py", line 243, in parallel_download
    list(executor.map(download_part, tasks))
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/file_download.py", line 203, in download_part
    for chunk in r.iter_content(chunk_size=API_FILE_DOWNLOAD_CHUNK_SIZE):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='[www.modelscope.cn](http://www.modelscope.cn/)', port=80): Read timed out.
Downloading:  91% 2.92G/3.20G [06:17<00:35, 8.31MB/s]
instance_data_dir /tmp/qw/training_data/YorickHe/majicmixRealistic_v6/test
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "/content/facechain/app.py", line 428, in run
    train_lora_fn(base_model_path=base_model_path,
  File "/content/facechain/app.py", line 87, in train_lora_fn
    validation_prompt, _ = get_popular_prompts(output_img_dir)
  File "/content/facechain/facechain/data_process/preprocessing.py", line 26, in get_popular_prompts
    f = open(os.path.join(train_dir, 'metadata.jsonl'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qw/training_data/YorickHe/majicmixRealistic_v6/test_labeled/metadata.jsonl'
--------uuid:  qw
----------work_dir:  /tmp/qw/ly261666/cv_portrait_model/test
2023-09-02 05:27:37,860 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:27:38,710 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:27:39,524 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:27:40,163 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:27:40,916 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:27:41,672 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-09-02 05:27:45,960 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-02 05:27:45,963 - modelscope - INFO - TensorFlow version 2.12.0 Found.
2023-09-02 05:27:45,963 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-09-02 05:27:45,998 - modelscope - INFO - Loading done! Current index file version is 1.8.4, with md5 51a048dace3a110560e1ffb667782db4 and a total number of 902 components indexed
2023-09-02 05:27:48.060805: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/content/facechain/app.py:659: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
/content/facechain/app.py:706: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  gallery = gr.Gallery(template_gallery_list).style(grid=4, height=300)
/content/facechain/app.py:706: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  gallery = gr.Gallery(template_gallery_list).style(grid=4, height=300)
/content/facechain/app.py:757: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
2023-09-02 05:27:53,303 - modelscope - INFO - Use user-specified model revision: v4.0
Downloading: 100% 3.20G/3.20G [00:38<00:00, 88.4MB/s]
Downloading:  84% 2.69G/3.20G [01:31<00:17, 31.6MB/s]Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 814, in _raw_read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 799, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.10/http/client.py", line 466, in read
    s = self.fp.read(amt)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 940, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 879, in read
    data = self._raw_read(amt)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 813, in _raw_read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/facechain/facechain/inference.py", line 24, in _data_process_fn_process
    Blipv2()(input_img_dir)
  File "/content/facechain/facechain/data_process/preprocessing.py", line 314, in __init__
    self.model = DeepDanbooru()
  File "/content/facechain/facechain/data_process/deepbooru.py", line 721, in __init__
    snapshot_path = snapshot_download(foundation_model_id, revision='v4.0')
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/snapshot_download.py", line 140, in snapshot_download
    parallel_download(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/file_download.py", line 243, in parallel_download
    list(executor.map(download_part, tasks))
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/hub/file_download.py", line 203, in download_part
    for chunk in r.iter_content(chunk_size=API_FILE_DOWNLOAD_CHUNK_SIZE):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
Downloading:  84% 2.69G/3.20G [05:50<01:07, 8.24MB/s]
instance_data_dir /tmp/qw/training_data/ly261666/cv_portrait_model/test
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "/content/facechain/app.py", line 428, in run
    train_lora_fn(base_model_path=base_model_path,
  File "/content/facechain/app.py", line 87, in train_lora_fn
    validation_prompt, _ = get_popular_prompts(output_img_dir)
  File "/content/facechain/facechain/data_process/preprocessing.py", line 26, in get_popular_prompts
    f = open(os.path.join(train_dir, 'metadata.jsonl'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qw/training_data/ly261666/cv_portrait_model/test_labeled/metadata.jsonl'

**Comment by whiteewei** [comment]
Sorry for duplicated.

**Comment by whiteewei** [comment]
Sorry for duplicated
