### ISSUE TITLE
PYTHONPATH=. sh train_lora_test.sh "ly261666/cv_portrait_model" "v2.0" "film/film" "./imgs" "./processed" "./output"     error

### ISSUE THREAD

**Issue by Aruen24** [modelscope/facechain#176]
`Traceback (most recent call last):
  File "facechain/train_text_to_image_lora.py", line 1469, in <module>
    main()
  File "facechain/train_text_to_image_lora.py", line 774, in main
    accelerator = Accelerator(
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/accelerator.py", line 364, in __init__
    self.state = AcceleratorState(
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/state.py", line 724, in __init__
    PartialState(cpu, **kwargs)
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/state.py", line 200, in __init__
    torch.cuda.set_device(self.device)
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2023-09-05 10:21:56,106 - modelscope - INFO - Use user-specified model revision: v2.0
{'dynamic_thresholding_ratio', 'sample_max_value', 'clip_sample_range', 'thresholding', 'variance_type'} was not found in config. Values will be initialized to default values.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 238213 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 238214) of binary: /home/wyw/anaconda3/envs/facechain/bin/python
Traceback (most recent call last):
  File "/home/wyw/anaconda3/envs/facechain/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wyw/anaconda3/envs/facechain/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================`
facechain/train_text_to_image_lora.py FAILED

Change to single GPU also error 
CUDA_VISIBLE_DEVICES=0 accelerate launch facechain/train_text_to_image_lora.py

**Comment by sunbaigui** [comment]
please provide the detail env & system.

**Comment by Aruen24** [comment]
> 

Ubuntu 20.04.4   CUDA Version: 12.1  Python 3.8.13  torch 2.0.0+cu117

**Comment by Aruen24** [comment]
> please provide the detail env & system.

@sunbaigui    Ubuntu 20.04.4 CUDA Version: 12.1 Python 3.8.13 torch 2.0.0+cu117

**Comment by Aruen24** [comment]
@sunbaigui 帮忙看看

**Comment by ultimatech-cn** [comment]
The main reasons for this error are primarily due to GPU issues or mismatched CUDA installation versions.
My suggestion as following.
1. use  python command in same env to check cuda
          import torch # 如果pytorch安装成功即可导入
          print(torch.cuda.is_available()) # 查看CUDA是否可用
          print(torch.cuda.device_count()) # 查看可用的CUDA数量
          print(torch.version.cuda) # 查看CUDA的版本号
2. run  python facechain/train_text_to_image_lora.py first to avoid accelerate's error
3. there is  default accelerate's setting, you should check it

**Comment by Aruen24** [comment]
@ultimatech-cn 
I change train_lora.sh
export MODEL_NAME=$1
export VERSION=$2
export SUB_PATH=$3
export DATASET_NAME=$4
export OUTPUT_DATASET_NAME=$5
export WORK_DIR=$6

python facechain/train_text_to_image_lora.py \
    --pretrained_model_name_or_path=$MODEL_NAME \
    --revision=$VERSION \
    --sub_path=$SUB_PATH \
    --dataset_name=$DATASET_NAME \
    --output_dataset_name=$OUTPUT_DATASET_NAME \
    --caption_column="text" \
    --resolution=512 --random_flip \
    --train_batch_size=1 \
    --num_train_epochs=200 --checkpointing_steps=5000 \
    --learning_rate=1.5e-04 --lr_scheduler="cosine" --lr_warmup_steps=0 \
    --seed=42 \
    --output_dir=$WORK_DIR \
    --lora_r=4 --lora_alpha=32 \
    --lora_text_encoder_r=32 --lora_text_encoder_alpha=32 --resume_from_checkpoint='fromfacecommon'


And run PYTHONPATH=. sh train_lora.sh "ly261666/cv_portrait_model" "v2.0" "film/film" "./imgs" "./processed" "./output"
The result no error and solve the problem.  So its accelerate's error.
