### ISSUE TITLE
CUDA is not available issue with colab

### ISSUE THREAD

**Issue by kotaxyz** [modelscope/facechain#20]
all works fine but when start training i get this error 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "/content/facechain/app.py", line 123, in run
    raise gr.Error('CUDA is not available.')
gradio.exceptions.Error: 'CUDA is not available.'

**Comment by wangxingjun778** [comment]
> all works fine but when start training i get this error Traceback ...

Is cuda available ? Please check it.

import torch
torch.cuda.is_available()

**Comment by wangxingjun778** [comment]
> 

And please make sure you have at least 19GB GPU MEM.  Nvidia A100(40G)、A10(24G) are recommended on Colab.  

In addition, we are planning to support 16G GPU MEM like V100(16G) device in the near future. ^^
