### ISSUE TITLE
训练会报错呢

### ISSUE THREAD

**Issue by joisonwk** [modelscope/facechain#205]
--------uuid:  qw
----------work_dir:  /tmp/qw/YorickHe/majicmixRealistic_v6/xxx
2023-09-10 20:03:43,867 - modelscope - INFO - Use user-specified model revision: v1.0.0
Traceback (most recent call last):
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/home/ant/images/facechain/app.py", line 464, in run
    prepare_dataset([img['name'] for img in instance_images], output_dataset_dir=instance_data_dir)
  File "/home/ant/images/facechain/facechain/train_text_to_image_lora.py", line 195, in prepare_dataset
    image = get_rot(image)
  File "/home/ant/images/facechain/facechain/train_text_to_image_lora.py", line 146, in get_rot
    ort_session = onnxruntime.InferenceSession(model_path)
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 396, in __init__
    raise e
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/ant/miniconda3/envs/py39/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 415, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by sunbaigui** [comment]
看起来是哪些库版本没对齐。你的系统是？

**Comment by joisonwk** [comment]
系统是wsl2+ubuntu22.04, 
检查发现onnxruntime1.15.1包不支持onnxruntime.InferenceSession()初始化providers为None的fallback()重试，手动注释调文件onnxruntime_inference_collection.py 414行的代码self.disable_fallback()就可以通过了。

**Comment by ZhiwenDeng-dev** [comment]
手动注释 self.disable_fallback() 后，训练时使用的都是CPU，GPU没有工作了

**Comment by ZhiwenDeng-dev** [comment]
def _create_inference_session(self, providers, provider_options, disabled_optimizers=None):
        available_providers = C.get_available_providers()

        # Tensorrt can fall back to CUDA. All others fall back to CPU.
        if "TensorrtExecutionProvider" in available_providers:
            self._fallback_providers = ["CUDAExecutionProvider", "CPUExecutionProvider"]
        elif "MIGraphXExecutionProvider" in available_providers:
            self._fallback_providers = ["ROCMExecutionProvider", "CPUExecutionProvider"]
        else:
            self._fallback_providers = ["CPUExecutionProvider"]

        # validate providers and provider_options before other initialization
        providers, provider_options = check_and_normalize_provider_args(
            providers, provider_options, available_providers
        )
        if not providers and len(available_providers) > 1:
            self.disable_fallback()
            raise ValueError(
                f"This ORT build has {available_providers} enabled. "
                "Since ORT 1.9, you are required to explicitly set "
                "the providers parameter when instantiating InferenceSession. For example, "
                f"onnxruntime.InferenceSession(..., providers={available_providers}, ...)"
            )
