### ISSUE TITLE
关于cuda11.7

### ISSUE THREAD

**Issue by yinghanzi** [modelscope/facechain#22]
我在部署facechain的时候，系统要求cuda11.7，可是在ubuntu上的 4090对应的显卡驱动都是支持的cuda12.2的，安装不上11.7。请问是不是cuda12.2 的也可以，为什么我的这边一直报错，训练的时候。。

还有两个问题：
1: 如果conda安装的python3.10.6的时候，如果是cuda12.2，那么mim install mmcv-full==1.7.0压根就无法执行安装
2: 但是如果用python3.8的话是可以安装成功mim install mmcv-full==1.7.0，启动程序，但是训练的时候报错。

**Comment by RickyWang111** [comment]
我的是3090  驱动也是只支持12.2，我猜测可能要卸载驱动，重新安装对应的老驱动

**Comment by yinghanzi** [comment]
2023-08-16 15:13:09,794 - mmcv - INFO - 
pafpn_convs.1.conv.bias - torch.Size([16]): 
The value is the same before and after calling `init_weights` of PAFPN  
 
2023-08-16 15:13:09,794 - modelscope - INFO - loading model from /home/adu/.cache/modelscope/hub/damo/cv_ddsar_face-detection_iclr23-damofd/pytorch_model.pt
load checkpoint from local path: /home/adu/.cache/modelscope/hub/damo/cv_ddsar_face-detection_iclr23-damofd/pytorch_model.pt
2023-08-16 15:13:09,806 - modelscope - INFO - load model done
2023-08-16 15:13:09,815 - modelscope - INFO - loading model from /home/adu/.cache/modelscope/hub/damo/cv_manual_facial-landmark-confidence_flcm/pytorch_model.pt
2023-08-16 15:13:09,823 - modelscope - INFO - load model done
cathed for image process of 001.jpg
Error: nms_impl: implementation for device cuda:0 not found.

cathed for image process of 002.jpg
Error: nms_impl: implementation for device cuda:0 not found.

cathed for image process of 003.jpg
Error: nms_impl: implementation for device cuda:0 not found.

cathed for image process of 000.jpg
Error: nms_impl: implementation for device cuda:0 not found.

[]
Error: result is empty.
Traceback (most recent call last):
  File "/home/adu/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/adu/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/adu/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/adu/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/adu/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/adu/anaconda3/envs/facechain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/adu/anaconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 149, in run
    data_process_fn(instance_data_dir, True)
  File "/home/adu/Documents/facechain/facechain/inference.py", line 24, in data_process_fn
    out_json_name = data_process_fn(input_img_dir)
  File "/home/adu/Documents/facechain/facechain/data_process/preprocessing.py", line 335, in __call__
    exit()
  File "/home/adu/anaconda3/envs/facechain/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by yinghanzi** [comment]
> 我的是3090 驱动也是只支持12.2，我猜测可能要卸载驱动，重新安装对应的老驱动

安装cuda11.7的话，对应的显卡驱动也要换，当时已经找不到支持4090对应显卡驱动了。

**Comment by wangxingjun778** [comment]
cuda12.2还未做适配验证，我们测一下。

**Comment by yinghanzi** [comment]
> cuda12.2还未做适配验证，我们测一下。

4090显卡目前没有匹配cuda11.7的驱动了。另外官方写的是ubuntu20.04,请问22.04是不是也还没有做适配了？22.04的个人主机用户挺多的。谢谢。

**Comment by yinghanzi** [comment]
> cuda12.2还未做适配验证，我们测一下。

我在conda是可以安装cuda11.7的，但是虚拟环境没有nvcc，在训练的时候依然报错 （奇怪，为什么我电脑上的Stable diffusion等别的项目都没遇到过这个问题呢）

**Comment by keepacat** [comment]
俺也一样，cuda 12.2的，死活都编译不过

**Comment by ultimatech-cn** [comment]
我也刚踩了这个坑，12.2降级到11.8， 重装了 anaconda。最后总结一下，上是pytorch的问题，只要pytorch正确安装就行，cuda和pytorch的版本一致就行。
最主要的是mmcv-full这个包，不能mim方式安装，要pip方式安装。

**Comment by aetherwu** [comment]
> cuda11.7

Windows 10.
4090 Latest driver.

排队再等等。

**Comment by ultimatech-cn** [comment]
这个错误好眼熟，不外乎三个解决方法：1.卸载torch，重装和你显卡匹配的，2.重装numpy，3. pip安装mmcv-full
可以参考
https://zhuanlan.zhihu.com/p/651180440

**Comment by ywj5782** [comment]
> 我在部署facechain的时候，系统要求cuda11.7，但是在ubuntu上的4090对应的显卡驱动都是支持cuda12.2的，安装不上11.7。请问不是cuda12.2的也可以，为什么我的香料一直报错，训练的时候。。
> 
> 还有问题： 1: 如果conda两个安装的python3.10.6的时候，如果是cuda12.2，那么mim install mmcv-full==1.7.0压根就无法执行安装 2: 但是如果用python3.8的话是安装可以成功mim install mmcv-full==1.7.0，启动程序，但是训练的时候报错。


https://developer.nvidia.com/cuda-toolkit-archive
