### ISSUE TITLE
Error: result is empty.

### ISSUE THREAD

**Issue by hasu234** [modelscope/facechain#23]
[]
Error: result is empty.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "/content/facechain/app.py", line 149, in run
    data_process_fn(instance_data_dir, True)
  File "/content/facechain/facechain/inference.py", line 24, in data_process_fn
    out_json_name = data_process_fn(input_img_dir)
  File "/content/facechain/facechain/data_process/preprocessing.py", line 335, in __call__
    exit()
  File "/usr/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

When running on Colab (t4 Runtime)

**Comment by wangxingjun778** [comment]
> [] Error: result is empty. Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict output = await app.get_blocks().process_api( File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api result = await self.call_function( File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function prediction = await anyio.to_thread.run_sync( File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 706, in wrapper response = f(*args, **kwargs) File "/content/facechain/app.py", line 149, in run data_process_fn(instance_data_dir, True) File "/content/facechain/facechain/inference.py", line 24, in data_process_fn out_json_name = data_process_fn(input_img_dir) File "/content/facechain/facechain/data_process/preprocessing.py", line 335, in **call** exit() File "/usr/lib/python3.10/_sitebuiltins.py", line 26, in **call** raise SystemExit(code) SystemExit: None
> 
> When running on Colab (t4 Runtime)


Please check the mmcv-full dependency, the wheel installing method may not compatible with your env, you can use mimm install mmcv-full==1.7.0, refer to: https://colab.research.google.com/drive/1cUhnVXseqD2EJiotZk3k7GsfQK9_yJu_?usp=sharing

In addition, the cost of GPU could be about 19G, so A100(40G)  or A10(24G) are recommended.

**Comment by hasu234** [comment]
Alternative manual installation of mmcv-full dependency using 
```
!pip3 install -U openmim
!mim install mmcv-full==1.7.0
```
has solved the issue for me with a better GPU
