### ISSUE TITLE
Model not existing 

### ISSUE THREAD

**Issue by AMEERAZAM08** [modelscope/facechain#300]
self.skin_retouching = pipeline('skin-retouching-torch', model='damo/cv_unet_skin_retouching_torch', model_revision='v1.0.1')
getting this 
modelscope - WARNING - Find task: skin-retouching-torch, model type: None. Insufficient information to build preprocessor, skip building preprocessor

**Comment by AMEERAZAM08** [comment]
if model existing then ot will donwload automatic

**Comment by AMEERAZAM08** [comment]
if possible can you share conda env file  ..  @sunbaigui @wenmengzhou @yingdachen @justmywyw

**Comment by AMEERAZAM08** [comment]
while loading this 
fair_face_attribute_func = pipeline(Tasks.face_attribute_recognition,'damo/cv_resnet34_face-attribute-recognition_fairface', model_revision='v2.0.2')
system-Linux 
Nvidia-3090ti

error 
ImportError: FaceAttributeRecognitionPipeline: FaceDetectionPipeline: DamoFdDetect: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/rnd/miniconda3/envs/facechain/lib/python3.10/site-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so)

**Comment by AMEERAZAM08** [comment]
now getting this 
2023-09-17 01:47:23,291 - modelscope - INFO - Use user-specified model revision: v1.0.0
Resuming from checkpoint /home/ /.cache/modelscope/hub/damo/face_frombase_c4/face_frombase_c4.bin
Steps:   0%|                                                                                                                             | 0/200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ /Documents/Ameer/facechain/facechain/train_text_to_image_lora.py", line 1167, in <module>
    main()
  File "/home/ /Documents/Ameer/facechain/facechain/train_text_to_image_lora.py", line 988, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/miniconda3/envs/facechain/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

**Comment by AMEERAZAM08** [comment]
all working
