### ISSUE TITLE
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled

### ISSUE THREAD

**Issue by ZhiwenDeng-dev** [modelscope/facechain#319]
`Traceback (most recent call last):
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/gradio/utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 489, in run
    prepare_dataset([img['name'] for img in instance_images], output_dataset_dir=instance_data_dir)
  File "/root/facechain/facechain/train_text_to_image_lora.py", line 193, in prepare_dataset
    image = get_rot(image)
  File "/root/facechain/facechain/train_text_to_image_lora.py", line 144, in get_rot
    ort_session = onnxruntime.InferenceSession(model_path)
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/miniconda3/envs/facechain/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)`

用autodl的环境部署时，报错，注释onnxruntime_inference_collection.py 文件的self.disable_fallback() 可以运行，但是无法使用GPU进行推理

**Comment by hoveychen** [comment]
刚刚遇到这个问题。10个小时前看onnxruntime的新版有breaking change。
降版本能解决
```
pip install onnxruntime==1.15.1
```

**Comment by ZhiwenDeng-dev** [comment]
其他步骤按git操作就可以了吗

**Comment by ZhiwenDeng-dev** [comment]
是python 3.10的环境吗

**Comment by ZhiwenDeng-dev** [comment]
执行 「pip install onnxruntime==1.15.1」已解决，python环境3.8，其他步骤按README执行即可

**Comment by sunbaigui** [comment]
closed as solved
