### ISSUE TITLE
colab运行报错

### ISSUE THREAD

**Issue by aimdreamboy** [modelscope/facechain#324]
报错信息如下，如何解决？
有社群吗？
--------uuid:  qw
----------work_dir:  /tmp/qw/ly261666/cv_portrait_model/person1
2023-09-23 14:17:59,031 - modelscope - INFO - Use user-specified model revision: v1.0.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "/content/facechain/app.py", line 489, in run
    prepare_dataset([img['name'] for img in instance_images], output_dataset_dir=instance_data_dir)
  File "/content/facechain/facechain/train_text_to_image_lora.py", line 193, in prepare_dataset
    image = get_rot(image)
  File "/content/facechain/facechain/train_text_to_image_lora.py", line 144, in get_rot
    ort_session = onnxruntime.InferenceSession(model_path)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by Husky110** [comment]
I don't speak chinese and came here just by mistake actually :sweat_smile: 
But seeing the error - I had the same problem.
Just open facechain/text_to_image_lora.py and change like 144 to `ort_session = onnxruntime.InferenceSession(model_path,providers=onnxruntime.get_all_providers())` and it will work - until you run in the runtime-error "context already set" tho...

**Comment by watt1010** [comment]
把onnxruntime的版本由1.16.0改成1.15.0
