### ISSUE TITLE
No such file or directory: 'ffprobe'

### ISSUE THREAD

**Issue by ryanicer** [modelscope/facechain#345]
ubuntu 20 + anaconda 安装，之前已经安装成功，并可以正常运行，今天更新后使用新的人物视频说话功能报error，具体error如下：
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.
/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/processing_utils.py", line 145, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/blocks.py", line 1435, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/blocks.py", line 1245, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/components/audio.py", line 220, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/processing_utils.py", line 155, in audio_from_file
    raise RuntimeError(msg) from e
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.
![Dingtalk_20231008121957](https://github.com/modelscope/facechain/assets/40254423/fcb469de-5f77-4043-b2f6-a45750fe2166)

**Comment by wwdok** [comment]
@ryanicer 新的人物视频说话功能需要依赖ffmpeg，您看一下这里的文档：https://github.com/modelscope/facechain/blob/main/doc/installation_for_talkinghead_ZH.md#3%E5%AE%89%E8%A3%85ffmpeg，检查是否安装ffmpeg，如果`ffmpeg -version`正常还报这个错，那可能是您安装的ffmpeg不完整，您可以按照文档重装一下ffmpeg，或者通过以下方式重装：
```
sudo apt autoremove ffmpeg -y
wget https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-5.1.1-amd64-static.tar.xz
tar -xf ffmpeg-5.1.1-amd64-static.tar.xz
cd ffmpeg-5.1.1-amd64-static
cp ./ffmpeg /usr/local/bin/
cp ./ffprobe /usr/local/bin/
```

**Comment by ryanicer** [comment]
感谢，确实发ffmpeg的问题，已经按文档上步骤安装了。但是运行时又报了新的问题，如下：
2023-10-11 12:24:35,022 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-10-11 12:24:35,023 - modelscope - INFO - Loading ast index from /home/nick/.cache/modelscope/ast_indexer
2023-10-11 12:24:35,049 - modelscope - INFO - Loading done! Current index file version is 1.9.0, with md5 3b1d3e7b5762341856ec98ea93241bfe and a total number of 921 components indexed
/home/nick/proj/ai/facechain/app.py:915: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['resources/inpaint_template/2.jpg'], ['resources/inpaint_template/3.jpg'], ['resources/inpaint_template/5.jpg'], ['resources/inpaint_template/4.jpg'], ['resources/inpaint_template/1.jpg']]
/home/nick/proj/ai/facechain/app.py:1017: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
2023-10-11 12:24:37,417 - modelscope - INFO - Use user-specified model revision: v1.0.0
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/nick/proj/ai/facechain/facechain/inference_talkinghead.py", line 36, in __call__
    inference = pipeline('talking-head', model='wwd123/sadtalker', model_revision='v1.0.0')
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 121, in pipeline
    register_modelhub_repo(model, cfg.get('allow_remote', False))
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/utils/plugins.py", line 456, in register_modelhub_repo
    import_module_from_model_dir(model_dir)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/utils/plugins.py", line 401, in import_module_from_model_dir
    importlib.import_module(submodule)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/networks.py", line 18, in <module>
    from .arcface_torch.backbones import get_model
ImportError: cannot import name 'get_model' from 'sadtalker.src.face3d.models.arcface_torch.backbones' (/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/arcface_torch/backbones/__init__.py)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 503, in async_iteration
    return await iterator.__anext__()
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/nick/proj/ai/facechain/app.py", line 475, in launch_pipeline_talkinghead
    output = future.result()
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
ImportError: cannot import name 'get_model' from 'sadtalker.src.face3d.models.arcface_torch.backbones' (/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/arcface_torch/backbones/__init__.py)

**Comment by wwdok** [comment]
这是因为您的modelscope版本比较低的原因，最新版的modelscope已经修复了这个bug，请升级一下modelscope：`pip install -U modelscope`， 确保版本大于1.9.1

**Comment by ryanicer** [comment]
感谢耐心回复，已经按照要求更新了modelscope，当前版本为1.9.2
_Successfully installed modelscope-1.9.2_
遗憾的是，再次报错，错误信息如下：（报错后，重新更新了代码，依然报同样的错误）
2023-10-11 17:03:05,407 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-10-11 17:03:05,409 - modelscope - INFO - Loading ast index from /home/nick/.cache/modelscope/ast_indexer
2023-10-11 17:03:05,436 - modelscope - INFO - Loading done! Current index file version is 1.9.2, with md5 a178e21a4531358181c8f66e42dbd4f3 and a total number of 941 components indexed
/home/nick/proj/ai/facechain/app.py:915: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['resources/inpaint_template/2.jpg'], ['resources/inpaint_template/3.jpg'], ['resources/inpaint_template/5.jpg'], ['resources/inpaint_template/4.jpg'], ['resources/inpaint_template/1.jpg']]
/home/nick/proj/ai/facechain/app.py:1017: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
2023-10-11 17:03:07,810 - modelscope - INFO - Use user-specified model revision: v1.0.0
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/nick/proj/ai/facechain/facechain/inference_talkinghead.py", line 36, in __call__
    inference = pipeline('talking-head', model='wwd123/sadtalker', model_revision='v1.0.0')
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 133, in pipeline
    register_modelhub_repo(model, cfg.get('allow_remote', False))
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/utils/plugins.py", line 456, in register_modelhub_repo
    import_module_from_model_dir(model_dir)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/utils/plugins.py", line 401, in import_module_from_model_dir
    importlib.import_module(submodule)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/__init__.py", line 22, in <module>
    from src.face3d.models.base_model import BaseModel
  File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/__init__.py", line 22, in <module>
    from src.face3d.models.base_model import BaseModel
  File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/base_model.py", line 9, in <module>
    from . import networks
  File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/networks.py", line 19, in <module>
    from kornia.geometry import warp_affine
ModuleNotFoundError: No module named 'kornia'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 503, in async_iteration
    return await iterator.__anext__()
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 496, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 479, in run_sync_iterator_async
    return next(iterator)
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 629, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/nick/proj/ai/facechain/app.py", line 475, in launch_pipeline_talkinghead
    output = future.result()
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
ModuleNotFoundError: No module named 'kornia'

**Comment by sunbaigui** [comment]
@wwdok please check this at your convenience.

**Comment by wwdok** [comment]
报错信息里说：”ModuleNotFoundError: No module named 'kornia'“，您需要安装这些[依赖包](https://github.com/modelscope/facechain/blob/main/doc/installation_for_talkinghead_ZH.md#2%E5%AE%89%E8%A3%85python%E4%BE%9D%E8%B5%96%E5%8C%85)
![image](https://github.com/modelscope/facechain/assets/43233772/6f559c84-2fe3-4331-a823-3b195c3e0997)
