### ISSUE TITLE
bdb.BdbQuit

### ISSUE THREAD

**Issue by Aoing** [modelscope/facechain#351]
上传自己的风格 lora，并且输入了 prompt 之后，训练报错
 
![image](https://github.com/modelscope/facechain/assets/50202546/9141b856-e91b-4926-b72c-377a24d4f8c1)

```
/home/tantive4/facechain-new/facechain-latest/app.py:1017: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
/home/tantive4/facechain-new/facechain-latest/app.py:915: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['resources/inpaint_template/1.jpg'], ['resources/inpaint_template/2.jpg'], ['resources/inpaint_template/3.jpg'], ['resources/inpaint_template/4.jpg'], ['resources/inpaint_template/5.jpg']]
/home/tantive4/facechain-new/facechain-latest/app.py:1017: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
2023-10-11 15:22:51,561 - modelscope - INFO - Use user-specified model revision: v1.0.0
libpng error: Read Error
> /home/tantive4/facechain-new/facechain-latest/facechain/inference.py(515)compress_image()
-> compressed_image = cv2.imencode('.jpg', image, [cv2.IMWRITE_JPEG_QUALITY, quality])[1].tostring()
(Pdb)
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/envs/facechain-new/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/tantive4/facechain-new/facechain-latest/facechain/inference.py", line 484, in __call__
    gen_results = main_model_inference(self.pose_model_path, self.pose_image, self.use_depth_control,
  File "/home/tantive4/facechain-new/facechain-latest/facechain/inference.py", line 372, in main_model_inference
    pose_image = compress_image(pose_image, 1024 * 1024)
  File "/home/tantive4/facechain-new/facechain-latest/facechain/inference.py", line 515, in compress_image
    compressed_image = cv2.imencode('.jpg', image, [cv2.IMWRITE_JPEG_QUALITY, quality])[1].tostring()
  File "/home/tantive4/facechain-new/facechain-latest/facechain/inference.py", line 515, in compress_image
    compressed_image = cv2.imencode('.jpg', image, [cv2.IMWRITE_JPEG_QUALITY, quality])[1].tostring()
  File "/opt/conda/envs/facechain-new/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/opt/conda/envs/facechain-new/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/gradio/utils.py", line 349, in async_iteration
    return await iterator.__anext__()
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/gradio/utils.py", line 342, in __anext__
    return await anyio.to_thread.run_sync(
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/gradio/utils.py", line 325, in run_sync_iterator_async
    return next(iterator)
  File "/opt/conda/envs/facechain-new/lib/python3.8/site-packages/gradio/utils.py", line 694, in gen_wrapper
    yield from f(*args, **kwargs)
  File "app.py", line 271, in launch_pipeline
    outputs = future.result()
  File "/opt/conda/envs/facechain-new/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/conda/envs/facechain-new/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
bdb.BdbQuit

```

**Comment by sunbaigui** [comment]
@hehaha68 please check this at your convenience.

**Comment by ly19965** [comment]
pdb 引起的多线程bug, debug时不要用pdb，后者改成单线程debug
