### ISSUE TITLE
No module named 'kornia'

### ISSUE THREAD

**Issue by ryanicer** [modelscope/facechain#352]
接 #345 的问题
更新了modelscope，当前版本为1.9.2（Successfully installed modelscope-1.9.2）
遗憾的是，再次报错，错误信息如下：（报错后，重新更新了代码，依然报同样的错误）
2023-10-11 17:03:05,407 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-10-11 17:03:05,409 - modelscope - INFO - Loading ast index from /home/nick/.cache/modelscope/ast_indexer
2023-10-11 17:03:05,436 - modelscope - INFO - Loading done! Current index file version is 1.9.2, with md5 a178e21a4531358181c8f66e42dbd4f3 and a total number of 941 components indexed
/home/nick/proj/ai/facechain/app.py:915: GradioDeprecationWarning: The style method is deprecated. Please set these arguments in the constructor instead.
output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['resources/inpaint_template/2.jpg'], ['resources/inpaint_template/3.jpg'], ['resources/inpaint_template/5.jpg'], ['resources/inpaint_template/4.jpg'], ['resources/inpaint_template/1.jpg']]
/home/nick/proj/ai/facechain/app.py:1017: GradioDeprecationWarning: The style method is deprecated. Please set these arguments in the constructor instead.
output_images = gr.Gallery(
2023-10-11 17:03:07,810 - modelscope - INFO - Use user-specified model revision: v1.0.0
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
File "/home/nick/proj/ai/facechain/facechain/inference_talkinghead.py", line 36, in call
inference = pipeline('talking-head', model='wwd123/sadtalker', model_revision='v1.0.0')
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 133, in pipeline
register_modelhub_repo(model, cfg.get('allow_remote', False))
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/utils/plugins.py", line 456, in register_modelhub_repo
import_module_from_model_dir(model_dir)
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/modelscope/utils/plugins.py", line 401, in import_module_from_model_dir
importlib.import_module(submodule)
File "/home/nick/anaconda3/envs/fc/lib/python3.10/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 992, in _find_and_load_unlocked
File "", line 241, in _call_with_frames_removed
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/init.py", line 22, in
from src.face3d.models.base_model import BaseModel
File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/init.py", line 22, in
from src.face3d.models.base_model import BaseModel
File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/base_model.py", line 9, in
from . import networks
File "/home/nick/.cache/modelscope/modelscope_modules/sadtalker/src/face3d/models/networks.py", line 19, in
from kornia.geometry import warp_affine
ModuleNotFoundError: No module named 'kornia'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
output = await route_utils.call_process_api(
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
output = await app.get_blocks().process_api(
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
result = await self.call_function(
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/blocks.py", line 1123, in call_function
prediction = await utils.async_iteration(iterator)
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 503, in async_iteration
return await iterator.anext()
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 496, in anext
return await anyio.to_thread.run_sync(
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
return await future
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
result = context.run(func, *args)
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 479, in run_sync_iterator_async
return next(iterator)
File "/home/nick/anaconda3/envs/fc/lib/python3.10/site-packages/gradio/utils.py", line 629, in gen_wrapper
yield from f(*args, **kwargs)
File "/home/nick/proj/ai/facechain/app.py", line 475, in launch_pipeline_talkinghead
output = future.result()
File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/_base.py", line 451, in result
return self.__get_result()
File "/home/nick/anaconda3/envs/fc/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
ModuleNotFoundError: No module named 'kornia'

**Comment by sunbaigui** [comment]
merge to #345
