### ISSUE TITLE
选择风格报错list index out of range

### ISSUE THREAD

**Issue by zhangxiying** [modelscope/facechain#355]
运行app.py后，在页面上选择风格，报如何下错误，麻烦老师看一下
Traceback (most recent call last):
  File "/data/autopai/anaconda3/envs/zxy_facechain/lib/python3.10/site-packages/gradio/routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "/data/autopai/anaconda3/envs/zxy_facechain/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/data/autopai/anaconda3/envs/zxy_facechain/lib/python3.10/site-packages/gradio/blocks.py", line 1554, in process_api
    result = await self.call_function(
  File "/data/autopai/anaconda3/envs/zxy_facechain/lib/python3.10/site-packages/gradio/blocks.py", line 1192, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data/autopai/anaconda3/envs/zxy_facechain/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/autopai/anaconda3/envs/zxy_facechain/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/data/autopai/anaconda3/envs/zxy_facechain/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/data/autopai/anaconda3/envs/zxy_facechain/lib/python3.10/site-packages/gradio/utils.py", line 659, in wrapper
    response = f(*args, **kwargs)
  File "/data/zxy/facechain/app.py", line 51, in select_function
    style = matched[0]
IndexError: list index out of range

**Comment by zhangxiying** [comment]
将evt.value改为evt.value[1]后可以了
