### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by Arthur-McArthur** [modelscope/facechain#375]
Uploaded 10 pictures, ran the script and got this error:

Traceback (most recent call last):
  File "C:\AI\sdwebui 2\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\sdwebui 2\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\AI\sdwebui 2\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\sdwebui 2\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\sdwebui 2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\sdwebui 2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\sdwebui 2\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\AI\sdwebui 2\extensions\facechain\app.py", line 545, in run
    train_lora_fn(base_model_path=base_model_path,
  File "C:\AI\sdwebui 2\extensions\facechain\app.py", line 110, in train_lora_fn
    subprocess.run(command, check=True)
  File "C:\Users\arthu\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\arthu\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\arthu\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by alexbofa** [comment]
Hello, the same

**Comment by lunar-studio** [comment]
Same.

**Comment by sunbaigui** [comment]
@ly19965 please check on this.

**Comment by ly19965** [comment]
@wenmengzhou Please check on this when you are free

**Comment by ArnorWing** [comment]
I am getting this error. Anyone get this fixed?

**Comment by bent1e** [comment]
Same，Anyone get this fixed?

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
