### ISSUE TITLE
训练失败，请问怎么解决

### ISSUE THREAD

**Issue by rxz421** [modelscope/facechain#379]
2023-10-24 16:36:55,286 - modelscope - INFO - Use user-specified model revision: v2.0
{'sample_max_value', 'variance_type', 'thresholding', 'dynamic_thresholding_ratio', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
{'force_upcast'} was not found in config. Values will be initialized to default values.
{'dropout', 'attention_type'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/mnt/workspace/facechain/facechain/train_text_to_image_lora.py", line 1220, in <module>
    main()
  File "/mnt/workspace/facechain/facechain/train_text_to_image_lora.py", line 791, in main
    dataset = load_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datasets/load.py", line 1773, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.8/site-packages/datasets/load.py", line 1502, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/opt/conda/lib/python3.8/site-packages/datasets/load.py", line 1221, in dataset_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a dataset script at /mnt/workspace/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/luo_labeled/luo_labeled.py or any data file in the same directory.
训练失败，请问怎么解决

**Comment by liusheng1113** [comment]
我在另外一个 issue里回复了，这个删除掉把。你们同一个问题。

**Comment by aiXia121** [comment]
> 我在另外一个 issue里回复了，这个删除掉把。你们同一个问题。

whereis?
