### ISSUE TITLE
在colab跑起来出错

### ISSUE THREAD

**Issue by rwmjhb** [modelscope/facechain#38]
在colab上跑起来，用的是A100，到最后一步都正常，网页打开，上传照片后，点击开始训练，提示“CUDA is not available”
日志如下
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "/content/facechain/app.py", line 123, in run
    raise gr.Error('CUDA is not available.')
gradio.exceptions.Error: 'CUDA is not available.'

**Comment by tastelikefeet** [comment]
看起来是您的colab没有显卡或显卡不可用导致的，如果在国内可以尝试modelscope的notebook，链接在readme中有

**Comment by jjiikkkk** [comment]
要跑去魔塔用 哎

**Comment by sunbaigui** [comment]
其他平台的支持暂时先参考readme支持情况。每周官微会有进展同步。请关注。
