### ISSUE TITLE
训练失败，环境安装没有问题，已上传完整错误信息并标记重点

### ISSUE THREAD

**Issue by han51535** [modelscope/facechain#383]
2023-10-25 23:32:04,446 - modelscope - INFO - Use user-specified model revision: v2.0
{'dynamic_thresholding_ratio', 'thresholding', 'sample_max_value', 'clip_sample_range', 'variance_type'} was not found in config. Values will be initialized to default values.
{'force_upcast'} was not found in config. Values will be initialized to default values.
{'dropout', 'attention_type'} was not found in config. Values will be initialized to default values.

Traceback (most recent call last):
  File "/mnt/workspace/facechain/facechain/train_text_to_image_lora.py", line 1220, in <module>
    main()
  File "/mnt/workspace/facechain/facechain/train_text_to_image_lora.py", line 791, in main
    dataset = load_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datasets/load.py", line 1773, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.8/site-packages/datasets/load.py", line 1502, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/opt/conda/lib/python3.8/site-packages/datasets/load.py", line 1221, in dataset_module_factory
    raise FileNotFoundError(
**FileNotFoundError: Couldn't find a dataset script at /mnt/workspace/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/person1_labeled/person1_labeled.py or any data file in the same directory.**

Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
**subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '/mnt/workspace/facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=/mnt/workspace/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/person1', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=/mnt/workspace/facechain/worker_data/qw/ly261666/cv_portrait_model/person1', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.**

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 556, in run
    train_lora_fn(base_model_path=base_model_path,
  File "app.py", line 138, in train_lora_fn
    raise gr.Error("训练失败 (Training failed)")
**gradio.exceptions.Error: '训练失败 (Training failed)'**

**Comment by Style-lo** [comment]
楼主解决了，我也是这个问题

**Comment by liusheng1113** [comment]
pip install fsspec==2023.9.2  重新安装一下fsspec

**Comment by Style-lo** [comment]
> pip install fsspec==2023.9.2 重新安装一下fsspec 。 我也遇到了。 应该是这个datasets的版本问题

重新安装fsspec 还是会有这个问题

**Comment by slin000111** [comment]
验证modelscope1.9.3，onnxruntime降一下版本可以跑，pip install onnxruntime==1.15.1，其他依赖参考readme.md。

**Comment by han51535** [comment]
> 验证modelscope1.9.3，onnxruntime降一下版本可以跑，pip install onnxruntime==1.15.1，其他依赖参考readme.md。

感谢，按你的方法成功运行了！

**Comment by han51535** [comment]
> slin000111

我用楼下@slin000111的方法成功了。

**Comment by han51535** [comment]
> 楼主解决了，我也是这个问题

我用楼下@slin000111的方法成功了。

**Comment by han51535** [comment]
> pip install fsspec==2023.9.2 重新安装一下fsspec 。 我也遇到了。 应该是这个datasets的版本问题

我用楼下@slin000111的方法成功了。

**Comment by han51535** [comment]
将 onnxruntime 版本降至 1.15.1 解决了此 issues。

**Comment by qinguoliang** [comment]
> 验证modelscope1.9.3，onnxruntime降一下版本可以跑，pip install onnxruntime==1.15.1，其他依赖参考readme.md。

感谢 解决了问题
