### ISSUE TITLE
Stable Diffusion 插件版本，点开始训练会报错

### ISSUE THREAD

**Issue by Arasi2333** [modelscope/facechain#399]
显存足够
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/lib/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stable-diffusion-webui/lib/python3.11/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stable-diffusion-webui/lib/python3.11/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stable-diffusion-webui/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stable-diffusion-webui/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/root/stable-diffusion-webui/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stable-diffusion-webui/lib/python3.11/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/root/stable-diffusion-webui/extensions/facechain/app.py", line 533, in run
    output_model_name = slugify.slugify(output_model_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stable-diffusion-webui/lib/python3.11/site-packages/slugify.py", line 25, in slugify
    re.sub(r'[^\w\s-]', '',
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object

**Comment by wenmengzhou** [comment]
@ly19965 这个看起来是一个通用的问题，output_model_name是bytes会报这个错，  不过不是很理解为什么output_model_name会为bytes
