### ISSUE TITLE
please help me, I don’t understand what the problem is

### ISSUE THREAD

**Issue by corolorn** [modelscope/facechain#411]
I can’t install your plugin on automatic1111

```
..........Connected!
Python 3.10.6 (main, Aug  2 2022, 18:57:48) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
ReActor preheating... Device: CUDA
Launching Web UI with arguments: --no-download-sd-model --opt-sdp-no-mem-attention --no-half-vae --opt-channelslast
No module 'xformers'. Proceeding without it.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those addedd through the extra networks menu.
[-] ADetailer initialized. version: 23.11.0, num models: 9
2023-11-07 18:06:10,355 - ControlNet - INFO - ControlNet v1.1.415
ControlNet preprocessor location: C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\extensions\sd-webui-controlnet\annotator\downloads
2023-11-07 18:06:10,422 - ControlNet - INFO - ControlNet v1.1.415
sd-webui-prompt-all-in-one background API service started successfully.
18:06:10 - ReActor - STATUS - Running v0.5.0-a5
Loading weights [aadddd3d75] from C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\models\Stable-diffusion\deliberate_v3.safetensors
Creating model from config: C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\configs\v1-inference.yaml
*Deforum ControlNet support: enabled*
2023-11-07 18:06:11,920 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-11-07 18:06:11,921 - modelscope - INFO - Loading ast index from C:\Users\corol\.cache\modelscope\ast_indexer      
2023-11-07 18:06:12,161 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 1e5ed88df6b84d06e4c45af3a71c361d and a total number of 945 components indexed
*** Error executing callback ui_tabs_callback for C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\extensions\facechain\app.py", line 19, in <module>
        from facechain.inference_inpaint import GenPortrait_inpaint
      File "C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\extensions\facechain\facechain\inference_inpaint.py", line 13, in <module>
        from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, \
    ImportError: cannot import name 'StableDiffusionControlNetInpaintPipeline' from 'diffusers' (C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\venv\lib\site-packages\diffusers\__init__.py)

---
Running on local URL:  http://127.0.0.1:7860
Loading VAE weights specified in settings: C:\Users\corol\pinokio\api\sd-webui.pinokio.git\automatic1111\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: sdp-no-mem... done.
Model loaded in 2.7s (load weights from disk: 0.1s, create model: 0.6s, apply weights to model: 1.6s, load VAE: 0.1s).

To create a public link, set `share=True` in `launch()`.
Startup time: 16.9s (prepare environment: 3.3s, import torch: 2.1s, import gradio: 0.6s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, setup codeformer: 0.1s, load scripts: 4.8s, create ui: 2.3s, gradio launch: 2.2s, app_started_callback: 0.4s).
```
here is the list of installed plugins
![image](https://github.com/modelscope/facechain/assets/30048832/f4d96de1-2917-42ef-9fe6-f2567a06eba2)

**Comment by wenmengzhou** [comment]
https://github.com/huggingface/diffusers/issues/3140   you can refer to this issue and upgrade your diffusers

**Comment by taleksan** [comment]
Same error. And getting latest diffusers (diffusers-0.23.0) didn't help, still getting this error:

*** Error executing callback ui_tabs_callback for Z:\sd\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "Z:\sd\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "Z:\sd\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "Z:\sd\stable-diffusion-webui\extensions\facechain\app.py", line 19, in <module>
        from facechain.inference_inpaint import GenPortrait_inpaint
      File "Z:\sd\stable-diffusion-webui\extensions\facechain\facechain\inference_inpaint.py", line 13, in <module>
        from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, \
    ImportError: cannot import name 'StableDiffusionControlNetInpaintPipeline' from 'diffusers' (Z:\sd\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py)

**Comment by wenmengzhou** [comment]
try to see whether your installed diffuers has the right __init__.py ,   which contains "StableDiffusionControlNetPipeline"  as in https://github.com/huggingface/diffusers/blob/bfe94a3993e069bf386c84e16a84ebbecdd7c5db/src/diffusers/__init__.py#L247
