### ISSUE TITLE
FileNotFoundError ??

### ISSUE THREAD

**Issue by smacotela** [modelscope/facechain#413]
Traceback (most recent call last):
  File "E:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\A1111\stable-diffusion-webui\extensions\facechain\app.py", line 691, in run
    train_lora_fn(base_model_path=base_model_path,
  File "E:\A1111\stable-diffusion-webui\extensions\facechain\app.py", line 111, in train_lora_fn
    subprocess.run(command, check=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by ultimatech-cn** [comment]
It is seems the preprocess doesn't produce the right output. You may need to add all the output of console or just try to train the lora by direct python command to find the exactly window error.

**Comment by lunar-studio** [comment]
> It is seems the preprocess doesn't produce the right output. You may need to add all the output of console or just try to train the lora by direct python command to find the exactly window error.

On windows 11, how do you directly train the Lora?

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
