### ISSUE TITLE
Training error. Can't find solution

### ISSUE THREAD

**Issue by sithlord86** [modelscope/facechain#426]
The application keeps giving errors. I think it's several issues. I followed several instructions per issue (example mmcv is installed etc.)
Program won;t worl. This is the complete log of one failed instance. See below for errors at startup.

2023-11-12 17:32:49,813 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-12 17:32:52,587 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-12 17:32:54,968 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-12 17:32:58,880 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-12 17:33:02,790 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-12 17:33:04,873 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-12 17:33:08,137 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-12 17:33:10,184 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-12 17:33:14,333 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-11-12 17:33:14,335 - modelscope - INFO - Loading ast index from C:\Users\----\.cache\modelscope\ast_indexer
2023-11-12 17:33:14,424 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 dd5a27ca9d4436ad2520d9dbd2a1e1ea and a total number of 945 components indexed
2023-11-12 17:33:19,802 - modelscope - INFO - Use user-specified model revision: v4.0
2023-11-12 17:33:25,792 - modelscope - INFO - Use user-specified model revision: v1.0.1
2023-11-12 17:33:26,389 - modelscope - WARNING - ('PIPELINES', 'skin-retouching-torch', 'skin-retouching-torch') not found in ast index file
2023-11-12 17:33:26,389 - modelscope - INFO - initiate model from C:\Users\----\.cache\modelscope\hub\damo\cv_unet_skin_retouching_torch
2023-11-12 17:33:26,389 - modelscope - INFO - initiate model from location C:\Users\----\.cache\modelscope\hub\damo\cv_unet_skin_retouching_torch.
2023-11-12 17:33:26,392 - modelscope - WARNING - No preprocessor field found in cfg.
2023-11-12 17:33:26,392 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-11-12 17:33:26,392 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\----\\.cache\\modelscope\\hub\\damo\\cv_unet_skin_retouching_torch'}. trying to build by task and model information.
2023-11-12 17:33:26,392 - modelscope - WARNING - Find task: skin-retouching-torch, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-11-12 17:33:30,429 - modelscope - WARNING - Model revision not specified, use revision: v2.0.2
2023-11-12 17:33:32,401 - modelscope - INFO - initiate model from C:\Users\----\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
2023-11-12 17:33:32,401 - modelscope - INFO - initiate model from location C:\Users\----\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
2023-11-12 17:33:32,404 - modelscope - WARNING - No preprocessor field found in cfg.
2023-11-12 17:33:32,404 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-11-12 17:33:32,404 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\----\\.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-11-12 17:33:32,404 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-11-12 17:33:32,405 - modelscope - INFO - loading model from C:\Users\----\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
2023-11-12 17:33:32,711 - modelscope - INFO - load model done
2023-11-12 17:33:34.0289333 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2649'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0328524 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2644'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0356251 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2647'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0383554 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2658'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0410524 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2648'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0435427 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2657'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0465138 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2653'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0487649 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2652'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0509994 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2645'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0533713 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2643'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0562972 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2641'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0597671 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2633'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0625230 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2632'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0660682 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2624'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0690259 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2614'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0729213 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2613'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0763290 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2606'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0786353 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2598'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0824723 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2596'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:34.0847337 [W:onnxruntime:, graph.cc:3553 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2594'. It is not used by any node and should be removed from the model.
2023-11-12 17:33:37,333 - modelscope - INFO - Use user-specified model revision: v1.1
2023-11-12 17:33:37,860 - modelscope - INFO - initiate model from C:\Users\----\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd
2023-11-12 17:33:37,860 - modelscope - INFO - initiate model from location C:\Users\----\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd.
2023-11-12 17:33:37,861 - modelscope - INFO - initialize model from C:\Users\----\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\models\base\base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\models\cv\face_detection\scrfd\damofd_detect.py", line 31, in __init__
    super().__init__(model_dir, **kwargs)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\models\cv\face_detection\scrfd\scrfd_detect.py", line 36, in __init__
    from mmdet.models import build_detector
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\mmdet\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\mmdet\models\backbones\__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\mmdet\models\backbones\csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\mmdet\models\utils\__init__.py", line 13, in <module>
    from .point_sample import (get_uncertain_point_coords_with_randomness,
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\mmdet\models\utils\point_sample.py", line 3, in <module>
    from mmcv.ops import point_sample
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\cv\face_detection_pipeline.py", line 36, in __init__
    super().__init__(model=model, **kwargs)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\base.py", line 99, in __init__
    self.model = self.initiate_single_model(model)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: DamoFdDetect: No module named 'mmcv._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\----\stable-diffusion-webui\extensions\facechain\facechain\inference.py", line 24, in _data_process_fn_process
    Blipv2()(input_img_dir)
  File "C:\Users\----\stable-diffusion-webui\extensions\facechain\facechain\data_process\preprocessing.py", line 207, in __init__
    self.face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_ddsar_face-detection_iclr23-damofd', model_revision='v1.1')
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 164, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 67, in build_pipeline
    return build_from_cfg(
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: FaceDetectionPipeline: DamoFdDetect: No module named 'mmcv._ext'
instance_data_dir C:\Users\----\stable-diffusion-webui\extensions\facechain\worker_data\qw\training_data\ly261666/cv_portrait_model\----
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `0`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "C:\Users\----\stable-diffusion-webui\extensions\facechain\facechain\train_text_to_image_lora.py", line 32, in <module>
    import diffusers
ModuleNotFoundError: No module named 'diffusers'
Traceback (most recent call last):
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\----/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\----', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain\\worker_data\\qw\\ly261666/cv_portrait_model\\----', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
Error executing the command: Command '['accelerate', 'launch', 'C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\----', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain\\worker_data\\qw\\ly261666/cv_portrait_model\\----', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\----\stable-diffusion-webui\extensions\facechain\app.py", line 111, in train_lora_fn
    subprocess.run(command, check=True)
  File "C:\Users\----\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['accelerate', 'launch', 'C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\----', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain\\worker_data\\qw\\ly261666/cv_portrait_model\\----', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\----\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\----\stable-diffusion-webui\extensions\facechain\app.py", line 709, in run
    train_lora_fn(base_model_path=base_model_path,
  File "C:\Users\----\stable-diffusion-webui\extensions\facechain\app.py", line 114, in train_lora_fn
    raise gr.Error("训练失败 (Training failed)")
gradio.exceptions.Error: '训练失败 (Training failed)'

In addittion to this error after trying to train the model, the webui gives the following errors at startup:

venv "C:\Users\----\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --medvram --no-half-vae --listen --port=7860 --api --cors-allow-origins *
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
reading lora C:\Users\----\stable-diffusion-webui\models\Lora\babesBYSTABLEYOGI_v10.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\Users\----\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 35, in __init__
    self.metadata = cache.cached_data_for_file('safetensors-metadata', "lora/" + self.name, filename, read_metadata)
  File "C:\Users\----\stable-diffusion-webui\modules\cache.py", line 115, in cached_data_for_file
    value = func()
  File "C:\Users\----\stable-diffusion-webui\extensions-builtin\Lora\network.py", line 28, in read_metadata
    metadata = sd_models.read_metadata_from_safetensors(filename)
  File "C:\Users\----\stable-diffusion-webui\modules\sd_models.py", line 269, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\Users\----\stable-diffusion-webui\models\Lora\babesBYSTABLEYOGI_v10.safetensors is not a safetensors file

Loading weights [3c8530cb22] from C:\Users\----\stable-diffusion-webui\models\Stable-diffusion\cyberrealistic_v33.safetensors
Creating model from config: C:\Users\----\stable-diffusion-webui\configs\v1-inference.yaml
2023-11-12 17:19:29,129 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-11-12 17:19:29,132 - modelscope - INFO - Loading ast index from C:\Users\----\.cache\modelscope\ast_indexer
2023-11-12 17:19:29,243 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 dd5a27ca9d4436ad2520d9dbd2a1e1ea and a total number of 945 components indexed
Applying attention optimization: Doggettx... done.
C:\Users\----\stable-diffusion-webui\extensions\facechain\app.py:1012: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  image = gr.Image(source='webcam',type="filepath",visible=False).style(height=500,width=500)
C:\Users\----\stable-diffusion-webui\extensions\facechain\app.py:1156: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain/resources/inpaint_template\\1.jpg'], ['C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain/resources/inpaint_template\\2.jpg'], ['C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain/resources/inpaint_template\\3.jpg'], ['C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain/resources/inpaint_template\\4.jpg'], ['C:\\Users\\----\\stable-diffusion-webui\\extensions\\facechain/resources/inpaint_template\\5.jpg']]
C:\Users\----\stable-diffusion-webui\extensions\facechain\app.py:1258: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
[]
C:\Users\----\stable-diffusion-webui\extensions\facechain\app.py:1400: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
Running on local URL:  http://0.0.0.0:7860
Model loaded in 5.0s (load weights from disk: 0.4s, create model: 0.3s, apply weights to model: 0.4s, calculate empty prompt: 3.8s).

**Comment by ultimatech-cn** [comment]
it is seems caused by ModuleNotFoundError: DamoFdDetect: No module named 'mmcv._ext'
If you know how to use pip, you can try pip install mmcv-full in your webui venv.
And another common issue of windows platform is accelerate,  you can try use python directly instead of using acclerate launch

**Comment by sithlord86** [comment]
I did try to install mmcv again. I used both pip install MMCV-full as well as pip install MMCV.
MMCV-full gave the message the requirement was already met.
Install MMCV installed some other things.

Error remains the same.

I do not know how to use python directly instead of using accelerate launch. I'm at the top of my abilities, I barely get what everything does. I know how to use the UI and get some decent art out of it, but the coding goes straight over my head.

**Comment by ultimatech-cn** [comment]
You should 
pip install mmcv-full

not mmcv

**Comment by sithlord86** [comment]
it says MMCV-full is already installed. I uninstalled and installed it again. I tried updating it, it says it's already up to date. Here's the log I get when installing mmcv-full:

Requirement already satisfied: mmcv-full in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (1.7.1)
Requirement already satisfied: addict in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full) (2.4.0)
Requirement already satisfied: numpy in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full) (1.26.1)
Requirement already satisfied: packaging in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full) (23.2)
Requirement already satisfied: Pillow in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full) (10.1.0)
Requirement already satisfied: pyyaml in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full) (6.0.1)
Requirement already satisfied: yapf in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full) (0.40.2)
Requirement already satisfied: opencv-python>=3 in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full) (4.8.1.78)
Requirement already satisfied: regex in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full) (2023.10.3)
Requirement already satisfied: importlib-metadata>=6.6.0 in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from yapf->mmcv-full) (6.8.0)
Requirement already satisfied: platformdirs>=3.5.1 in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from yapf->mmcv-full) (4.0.0)
Requirement already satisfied: tomli>=2.0.1 in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from yapf->mmcv-full) (2.0.1)
Requirement already satisfied: zipp>=0.5 in c:\users\----\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=6.6.0->yapf->mmcv-full) (3.17.0)

**Comment by ultimatech-cn** [comment]
Please check the error message again.
If "ModuleNotFoundError: DamoFdDetect: No module named 'mmcv._ext'" still exist, it should be error of package installation.

**Comment by lunar-studio** [comment]
This error remains. I'm not sure if using TensorRT with this has anything to do with these errors. I have a 24G 3090 RTX on Win 11.

**Comment by HighOnTums** [comment]
@lunar-studio  same issue as you... 3080 here...  I'm afraid I may not be able to use the FaceChain extension b/c I don't know Python or have a desire to debug code right now lol

**Comment by ly19965** [comment]
Please refer to https://github.com/modelscope/facechain/issues/182.
