### ISSUE TITLE
errors with undefined symbol: _ZNK3c106SymIntltEl during training

### ISSUE THREAD

**Issue by mBerezovskyy** [modelscope/facechain#445]
During training I receive A few errors, namely 

- ImportError: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl
- ImportError: DamoFdDetect: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl
- ImportError: FaceDetectionPipeline: DamoFdDetect: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl

as well as 
- FileNotFoundError: Couldn't find a dataset script at /workspace/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/me2_labeled/me2_labeled.py or any data file in the same directory.

Please find the complete log below.

I am unaware of what to do, since I've only ran the pipeline and got the error immediately. Any help will be appreciated

2023-11-29 11:58:26,379 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-11-29 11:58:31,830 - modelscope - INFO - PyTorch version 2.1.0+cu118 Found.
2023-11-29 11:58:31,833 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-11-29 11:58:31,875 - modelscope - INFO - Loading done! Current index file version is 1.9.5, with md5 02febd683a9af26d5de93d288790bf07 and a total number of 945 components indexed
/workspace/facechain/app.py:1264: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['/workspace/facechain/resources/inpaint_template/1.jpg'], ['/workspace/facechain/resources/inpaint_template/2.jpg'], ['/workspace/facechain/resources/inpaint_template/3.jpg'], ['/workspace/facechain/resources/inpaint_template/4.jpg'], ['/workspace/facechain/resources/inpaint_template/5.jpg']]
/workspace/facechain/app.py:1367: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
[['resources/tryon_garment/garment1.png'], ['resources/tryon_garment/garment2.png'], ['resources/tryon_garment/garment3.png'], ['resources/tryon_garment/garment4.png']]
/workspace/facechain/app.py:1510: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(
2023-11-29 11:58:38,572 - modelscope - INFO - Use user-specified model revision: v4.0
2023-11-29 11:58:44,597 - modelscope - INFO - Use user-specified model revision: v1.0.1
Downloading: 100%|███████████████████████████| 121k/121k [00:00<00:00, 1.47MB/s]
Downloading: 100%|█████████████████████████████| 118/118 [00:00<00:00, 59.1kB/s]
Downloading: 100%|███████████████████████████| 146k/146k [00:00<00:00, 1.69MB/s]
Downloading: 100%|███████████████████████████| 217M/217M [00:07<00:00, 30.0MB/s]
Downloading: 100%|█████████████████████████| 97.8M/97.8M [00:02<00:00, 49.7MB/s]
Downloading: 100%|█████████████████████████| 12.4k/12.4k [00:00<00:00, 7.26MB/s]
Downloading: 100%|█████████████████████████| 51.2M/51.2M [00:01<00:00, 41.7MB/s]
Downloading: 100%|█████████████████████████| 4.90k/4.90k [00:00<00:00, 5.07MB/s]
Downloading: 100%|███████████████████████████| 104M/104M [00:02<00:00, 47.1MB/s]
Downloading: 100%|█████████████████████████| 76.4k/76.4k [00:00<00:00, 1.30MB/s]
Downloading: 100%|█████████████████████████| 82.0k/82.0k [00:00<00:00, 1.40MB/s]
2023-11-29 11:59:10,831 - modelscope - WARNING - ('PIPELINES', 'skin-retouching-torch', 'skin-retouching-torch') not found in ast index file
2023-11-29 11:59:10,831 - modelscope - INFO - initiate model from /root/.cache/modelscope/hub/damo/cv_unet_skin_retouching_torch
2023-11-29 11:59:10,831 - modelscope - INFO - initiate model from location /root/.cache/modelscope/hub/damo/cv_unet_skin_retouching_torch.
2023-11-29 11:59:10,833 - modelscope - WARNING - No preprocessor field found in cfg.
2023-11-29 11:59:10,833 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-11-29 11:59:10,833 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/root/.cache/modelscope/hub/damo/cv_unet_skin_retouching_torch'}. trying to build by task and model information.
2023-11-29 11:59:10,833 - modelscope - WARNING - Find task: skin-retouching-torch, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-11-29 11:59:16,829 - modelscope - WARNING - Model revision not specified, use revision: v2.0.2
Downloading: 100%|██████████████████████████████| 509/509 [00:00<00:00, 248kB/s]
Downloading: 100%|███████████████████████████| 104M/104M [00:02<00:00, 46.7MB/s]
Downloading: 100%|█████████████████████████| 5.78k/5.78k [00:00<00:00, 2.64MB/s]
Downloading: 100%|███████████████████████████| 980k/980k [00:00<00:00, 5.55MB/s]
Downloading: 100%|███████████████████████████| 137k/137k [00:00<00:00, 1.55MB/s]
2023-11-29 11:59:28,514 - modelscope - INFO - initiate model from /root/.cache/modelscope/hub/damo/cv_resnet50_face-detection_retinaface
2023-11-29 11:59:28,514 - modelscope - INFO - initiate model from location /root/.cache/modelscope/hub/damo/cv_resnet50_face-detection_retinaface.
2023-11-29 11:59:28,516 - modelscope - WARNING - No preprocessor field found in cfg.
2023-11-29 11:59:28,516 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-11-29 11:59:28,516 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/root/.cache/modelscope/hub/damo/cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-11-29 11:59:28,516 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-11-29 11:59:28,517 - modelscope - INFO - loading model from /root/.cache/modelscope/hub/damo/cv_resnet50_face-detection_retinaface/pytorch_model.pt
2023-11-29 11:59:29,101 - modelscope - INFO - load model done
2023-11-29 11:59:30.980673186 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2649'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980706806 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2657'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980712234 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2644'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980718387 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2594'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980726631 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2596'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980736959 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2653'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980743234 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2624'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980750943 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2652'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980761113 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2645'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980767152 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2643'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980776493 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2648'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980782942 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2647'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980789415 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2641'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980797308 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2633'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980819980 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2632'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980828207 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2614'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980834643 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2613'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980846135 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2658'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980855249 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2606'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:30.980860760 [W:onnxruntime:, graph.cc:3543 CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2598'. It is not used by any node and should be removed from the model.
2023-11-29 11:59:34,193 - modelscope - INFO - Use user-specified model revision: v1.1
Downloading: 100%|██████████████████████████████| 235/235 [00:00<00:00, 116kB/s]
Downloading: 100%|█████████████████████████| 5.82k/5.82k [00:00<00:00, 2.40MB/s]
Downloading: 100%|█████████████████████████| 2.17M/2.17M [00:00<00:00, 10.8MB/s]
Downloading: 100%|█████████████████████████| 8.10k/8.10k [00:00<00:00, 3.48MB/s]
2023-11-29 11:59:38,797 - modelscope - INFO - initiate model from /root/.cache/modelscope/hub/damo/cv_ddsar_face-detection_iclr23-damofd
2023-11-29 11:59:38,797 - modelscope - INFO - initiate model from location /root/.cache/modelscope/hub/damo/cv_ddsar_face-detection_iclr23-damofd.
2023-11-29 11:59:38,798 - modelscope - INFO - initialize model from /root/.cache/modelscope/hub/damo/cv_ddsar_face-detection_iclr23-damofd
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/models/base/base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/models/cv/face_detection/scrfd/damofd_detect.py", line 31, in __init__
    super().__init__(model_dir, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/models/cv/face_detection/scrfd/scrfd_detect.py", line 36, in __init__
    from mmdet.models import build_detector
  File "/usr/local/lib/python3.10/dist-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/usr/local/lib/python3.10/dist-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/usr/local/lib/python3.10/dist-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/usr/local/lib/python3.10/dist-packages/mmdet/models/utils/__init__.py", line 13, in <module>
    from .point_sample import (get_uncertain_point_coords_with_randomness,
  File "/usr/local/lib/python3.10/dist-packages/mmdet/models/utils/point_sample.py", line 3, in <module>
    from mmcv.ops import point_sample
  File "/usr/local/lib/python3.10/dist-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.10/dist-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/usr/local/lib/python3.10/dist-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/cv/face_detection_pipeline.py", line 36, in __init__
    super().__init__(model=model, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/base.py", line 99, in __init__
    self.model = self.initiate_single_model(model)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/models/base/base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/models/builder.py", line 35, in build_model
    model = build_from_cfg(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: DamoFdDetect: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/facechain/facechain/inference.py", line 25, in _data_process_fn_process
    Blipv2()(input_img_dir)
  File "/workspace/facechain/facechain/data_process/preprocessing.py", line 207, in __init__
    self.face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_ddsar_face-detection_iclr23-damofd', model_revision='v1.1')
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/builder.py", line 162, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ImportError: FaceDetectionPipeline: DamoFdDetect: /usr/local/lib/python3.10/dist-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl
instance_data_dir /workspace/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/me2
** project dir: /workspace/facechain
** params: >base_model_path:ly261666/cv_portrait_model, >revision:v2.0, >sub_path:film/film, >output_img_dir:/workspace/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/me2, >work_dir:/workspace/facechain/worker_data/qw/ly261666/cv_portrait_model/me2, >lora_r:4, >lora_alpha:32
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-11-29 11:59:48,298 - modelscope - INFO - PyTorch version 2.1.0+cu118 Found.
2023-11-29 11:59:48,300 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-11-29 11:59:48,344 - modelscope - INFO - Loading done! Current index file version is 1.9.5, with md5 02febd683a9af26d5de93d288790bf07 and a total number of 945 components indexed
/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:384: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
11/29/2023 11:59:50 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

2023-11-29 11:59:51,629 - modelscope - INFO - Use user-specified model revision: v2.0
{'sample_max_value', 'thresholding', 'variance_type', 'clip_sample_range', 'dynamic_thresholding_ratio'} was not found in config. Values will be initialized to default values.
{'force_upcast'} was not found in config. Values will be initialized to default values.
{'dropout', 'reverse_transformer_layers_per_block', 'attention_type'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/workspace/facechain/facechain/train_text_to_image_lora.py", line 1222, in <module>
    main()
  File "/workspace/facechain/facechain/train_text_to_image_lora.py", line 791, in main
    dataset = load_dataset(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1773, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1502, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1221, in dataset_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a dataset script at /workspace/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/me2_labeled/me2_labeled.py or any data file in the same directory.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/workspace/facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=/workspace/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/me2', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=/workspace/facechain/worker_data/qw/ly261666/cv_portrait_model/me2', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/facechain/app.py", line 799, in run
    train_lora_fn(base_model_path=base_model_path,
  File "/workspace/facechain/app.py", line 209, in train_lora_fn
    raise gr.Error("训练失败 (Training failed)")
gradio.exceptions.Error: '训练失败 (Training failed)'

**Comment by liuyhwangyh** [comment]
Please install mmcv with:  
min install mmcv-full==1.7.2
ref: https://mmcv.readthedocs.io/en/latest/get_started/installation.html
