### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionXLPipeline'

### ISSUE THREAD

**Issue by Cryyc** [modelscope/facechain#453]
Diffusers version is 0.25.0.dev0 atm, tried other versions too but I always get the import error. Checked the __init__.py file and it has StableDiffusionControlNetPipeline in it. Still the FaceChain tab won't appear in SD webui and I don't know what else to try in order to get it working. Any ideas why it doesn't work?

```
venv "C:\Users\user\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Installing requirements for diffusers
Installing requirements for Mov2mov
Installing requirements for imageio-ffmpeg
ReActor preheating... Device: CUDA
Launching Web UI with arguments: --xformers
2023-12-03 03:34:49,011 - ControlNet - INFO - ControlNet v1.1.419
ControlNet preprocessor location: C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-12-03 03:34:49,112 - ControlNet - INFO - ControlNet v1.1.419
03:34:50 - ReActor - STATUS - Running v0.5.1
Loading weights [ef76aa2332] from C:\Users\user\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
Creating model from config: C:\Users\user\stable-diffusion-webui\configs\v1-inference.yaml
2023-12-03 03:34:51,509 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-12-03 03:34:51,510 - modelscope - INFO - Loading ast index from C:\Users\user\.cache\modelscope\ast_indexer
2023-12-03 03:34:51,604 - modelscope - INFO - Loading done! Current index file version is 1.9.5, with md5 1abc39cf78daac13f0b488b3e4c7a559 and a total number of 945 components indexed
*** Error executing callback ui_tabs_callback for C:\Users\user\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "C:\Users\user\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\user\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "C:\Users\user\stable-diffusion-webui\extensions\facechain\app.py", line 16, in <module>
        from facechain.inference import preprocess_pose, GenPortrait
      File "C:\Users\user\stable-diffusion-webui\extensions\facechain\facechain\inference.py", line 10, in <module>
        from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, ControlNetModel, \
    ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' (C:\Users\user\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py)
```

**Comment by rugabunda** [comment]
Same problem here

**Comment by phillmorgan28** [comment]
Same problem here. Fresh 1111 install

**Comment by haiwang2517** [comment]
The issue with installing stable diffusion in Mac.

`2023-12-20 09:00:56,033 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-12-20 09:00:56,034 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2023-12-20 09:00:56,034 - modelscope - INFO - Loading ast index from /Users/ken/.cache/modelscope/ast_indexer
2023-12-20 09:00:56,110 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 398836bcb5b2492b717c43529abd309c and a total number of 946 components indexed
*** Error executing callback ui_tabs_callback for /Users/ken/software/ai/stable-diffusion-webui/extensions/facechain/scripts/facechain_sdwebui.py
    Traceback (most recent call last):
      File "/Users/ken/software/ai/stable-diffusion-webui/modules/script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "/Users/ken/software/ai/stable-diffusion-webui/extensions/facechain/scripts/facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "/Users/ken/software/ai/stable-diffusion-webui/extensions/facechain/app.py", line 16, in <module>
        from facechain.inference import preprocess_pose, GenPortrait
      File "/Users/ken/software/ai/stable-diffusion-webui/extensions/facechain/facechain/inference.py", line 10, in <module>
        from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, ControlNetModel, \
    ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' (/Users/ken/software/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/__init__.py)`

**Comment by yasainet** [comment]
Same problem 🥲

**Comment by deronkel82** [comment]
same here

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
