### ISSUE TITLE
Need explicit ORT provider setting

### ISSUE THREAD

**Issue by mangomingao** [modelscope/facechain#456]
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\xxx\.cache\modelscope\modelscope_modules\cv_unet_skin_retouching_torch\ms_wrapper.py", line 76, in __init__
    self.sess, self.input_node_name, self.out_node_name = self.load_onnx_model(
  File "C:\Users\xxx\.cache\modelscope\modelscope_modules\cv_unet_skin_retouching_torch\ms_wrapper.py", line 93, in load_onnx_model
    sess = onnxruntime.InferenceSession(onnx_path)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 388, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

Need to add providers for all InferenceSession

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
