### ISSUE TITLE
求助，4090显示内存不足18G，不知如何解决

### ISSUE THREAD

**Issue by 175Roy** [modelscope/facechain#457]
database is locked
Traceback (most recent call last):
  File "/app/stable-diffusion-webui/extensions/facechain/app.py", line 743, in run
    tensor = torch.empty((required_memory_bytes // 4,), device = device) # create 18GB tensor to check the memory if enough
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.00 GiB (GPU 0; 23.65 GiB total capacity; 2.09 GiB already allocated; 16.72 GiB free; 2.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/app/stable-diffusion-webui/extensions/facechain/app.py", line 747, in run
    raise gr.Error("目前显存不足18GB，训练失败！")
gradio.exceptions.Error: '目前显存不足18GB，训练失败！'
Traceback (most recent call last):
  File "/app/stable-diffusion-webui/extensions/facechain/app.py", line 743, in run
    tensor = torch.empty((required_memory_bytes // 4,), device = device) # create 18GB tensor to check the memory if enough
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.00 GiB (GPU 0; 23.65 GiB total capacity; 2.09 GiB already allocated; 16.72 GiB free; 2.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/app/stable-diffusion-webui/extensions/facechain/app.py", line 747, in run
    raise gr.Error("目前显存不足18GB，训练失败！")
gradio.exceptions.Error: '目前显存不足18GB，训练失败！'

**Comment by 175Roy** [comment]
另外安装facechain后无法启动webui，会卡在安装roop请求那一步

**Comment by Luojlong** [comment]
应该是显存不够吧，模型快20g，还有数据也会占很多

**Comment by wangxingjun778** [comment]
模型预计在lora training期间最高消耗约19G左右的GPU显存，所以推荐使用24GB 或以上的显卡。另外，我们最近在开展train free相关技术的研究，可以关注一下后续几个迭代。

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
