### ISSUE TITLE
FileNotFoundError: Couldn't find a dataset script 

### ISSUE THREAD

**Issue by lucifer726** [modelscope/facechain#462]
训练lora的时候出现这个报错：
Traceback (most recent call last):
  File "/root/autodl-tmp/hf-sd-webui/extensions/facechain/facechain/train_text_to_image_lora.py", line 1222, in <module>
    main()
  File "/root/autodl-tmp/hf-sd-webui/extensions/facechain/facechain/train_text_to_image_lora.py", line 791, in main
    dataset = load_dataset(
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/load.py", line 1773, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/load.py", line 1502, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/root/miniconda3/lib/python3.10/site-packages/datasets/load.py", line 1221, in dataset_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a dataset script at /root/autodl-tmp/hf-sd-webui/extensions/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/luoran_labeled/luoran_labeled.py or any data file in the same directory.
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '/root/autodl-tmp/hf-sd-webui/extensions/facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=/root/autodl-tmp/hf-sd-webui/extensions/facechain/worker_data/qw/training_data/ly261666/cv_portrait_model/luoran', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=/root/autodl-tmp/hf-sd-webui/extensions/facechain/worker_data/qw/ly261666/cv_portrait_model/luoran', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/root/autodl-tmp/hf-sd-webui/extensions/facechain/app.py", line 801, in run
    train_lora_fn(base_model_path=base_model_path,
  File "/root/autodl-tmp/hf-sd-webui/extensions/facechain/app.py", line 207, in train_lora_fn
    raise gr.Error("训练失败 (Training failed)")
gradio.exceptions.Error: '训练失败 (Training failed)'

**Comment by lucifer726** [comment]
@ly19965

**Comment by Augenstern000** [comment]
通过automatic1111 web ui或直接运行脚本试试呢

**Comment by thangnn1010** [comment]
Hi, Have you solved it yet? Can you give me some suggestions? thanks

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
