### ISSUE TITLE
Failure: --caption_column' value 'text' needs to be one of: image

### ISSUE THREAD

**Issue by kgallimore** [modelscope/facechain#469]
I am using the web ui extension
When trying to train on 3 images, it gets up to `Generating train split: 2 examples [00:08,  4.13s/ examples]` then fails
Version info: version: [v1.6.1] •  python: 3.10.6  •  torch: 1.13.1+cu116  •  xformers: N/A  •  gradio: 3.41.2

```
Generating train split: 2 examples [00:08,  4.13s/ examples]
Traceback (most recent call last):
  File "G:\ai\stableDiffusion\webui\extensions\facechain\facechain\train_text_to_image_lora.py", line 1222, in <module>
    main()
  File "G:\ai\stableDiffusion\webui\extensions\facechain\facechain\train_text_to_image_lora.py", line 829, in main
    raise ValueError(
ValueError: --caption_column' value 'text' needs to be one of: image
Error executing the command: Command '['python', 'G:\\ai\\stableDiffusion\\webui\\extensions\\facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=G:\\ai\\stableDiffusion\\webui\\extensions\\facechain\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\person2', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=G:\\ai\\stableDiffusion\\webui\\extensions\\facechain\\worker_data\\qw\\ly261666/cv_portrait_model\\person2', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "G:\ai\stableDiffusion\webui\extensions\facechain\app.py", line 147, in train_lora_fn
    subprocess.run(command, check=True)
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['python', 'G:\\ai\\stableDiffusion\\webui\\extensions\\facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=G:\\ai\\stableDiffusion\\webui\\extensions\\facechain\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\person2', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=G:\\ai\\stableDiffusion\\webui\\extensions\\facechain\\worker_data\\qw\\ly261666/cv_portrait_model\\person2', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\ai\stableDiffusion\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\ai\stableDiffusion\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\ai\stableDiffusion\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\ai\stableDiffusion\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\ai\stableDiffusion\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\ai\stableDiffusion\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\ai\stableDiffusion\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\ai\stableDiffusion\webui\extensions\facechain\app.py", line 801, in run
    train_lora_fn(base_model_path=base_model_path,
  File "G:\ai\stableDiffusion\webui\extensions\facechain\app.py", line 150, in train_lora_fn
    raise gr.Error("训练失败 (Training failed)")
gradio.exceptions.Error: '训练失败 (Training failed)'
```

**Comment by splitbot-tadeusz** [comment]
same here...

Downloading data files #0: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 998.64obj/s]
Downloading data files #1: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?obj/s]
Downloading data files #2: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?obj/s]
Downloading data files #3: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?obj/s]
Downloading data files #4: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?obj/s]
Downloading data files #5: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?obj/s]
Downloading data files #6: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?obj/s]
Downloading data files: 0it [00:00, ?it/s]
Extracting data files: 0it [00:00, ?it/s]                                                                                                                                                                                                                                                                                         | 0/1 [00:00<?, ?obj/s]
Setting num_proc from 8 to 7 for the train split as it only contains 7 shards.
12/11/2023 20:45:00 - WARNING - datasets.builder - Setting num_proc from 8 to 7 for the train split as it only contains 7 shards.                                                                                                                                                                                                 | 0/1 [00:00<?, ?obj/s]
Generating train split: 0 examples [00:00, ? examples/s]2023-12-11 20:45:07,117 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-11 20:45:07,123 - modelscope - INFO - Loading ast index from C:\Users\nikitin\.cache\modelscope\ast_indexer                                                                                                                                                                                                               | 0/1 [00:00<?, ?obj/s]
2023-12-11 20:45:07,155 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-11 20:45:07,161 - modelscope - INFO - Loading ast index from C:\Users\nikitin\.cache\modelscope\ast_indexer
2023-12-11 20:45:07,219 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-11 20:45:07,221 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-11 20:45:07,223 - modelscope - INFO - Loading ast index from C:\Users\nikitin\.cache\modelscope\ast_indexer
2023-12-11 20:45:07,234 - modelscope - INFO - Loading ast index from C:\Users\nikitin\.cache\modelscope\ast_indexer
2023-12-11 20:45:07,295 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-11 20:45:07,301 - modelscope - INFO - Loading ast index from C:\Users\nikitin\.cache\modelscope\ast_indexer
2023-12-11 20:45:07,353 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f835ac2d0f1c52e4c71ed7825b143343 and a total number of 946 components indexed
2023-12-11 20:45:07,360 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-11 20:45:07,363 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-11 20:45:07,373 - modelscope - INFO - Loading ast index from C:\Users\nikitin\.cache\modelscope\ast_indexer
2023-12-11 20:45:07,374 - modelscope - INFO - Loading ast index from C:\Users\nikitin\.cache\modelscope\ast_indexer
2023-12-11 20:45:07,398 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f835ac2d0f1c52e4c71ed7825b143343 and a total number of 946 components indexed
2023-12-11 20:45:07,436 - modelscope - INFO - PyTorch version 2.1.1 Found.
2023-12-11 20:45:07,442 - modelscope - INFO - Loading ast index from C:\Users\nikitin\.cache\modelscope\ast_indexer
2023-12-11 20:45:07,465 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f835ac2d0f1c52e4c71ed7825b143343 and a total number of 946 components indexed
2023-12-11 20:45:07,473 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f835ac2d0f1c52e4c71ed7825b143343 and a total number of 946 components indexed
2023-12-11 20:45:07,539 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f835ac2d0f1c52e4c71ed7825b143343 and a total number of 946 components indexed
2023-12-11 20:45:07,607 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f835ac2d0f1c52e4c71ed7825b143343 and a total number of 946 components indexed
2023-12-11 20:45:07,611 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f835ac2d0f1c52e4c71ed7825b143343 and a total number of 946 components indexed
2023-12-11 20:45:07,679 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 f835ac2d0f1c52e4c71ed7825b143343 and a total number of 946 components indexed
Generating train split: 7 examples [00:12,  1.72s/ examples]
Traceback (most recent call last):
  File "C:\SDWebUI\extensions\facechain\facechain\train_text_to_image_lora.py", line 1222, in <module>
    main()
  File "C:\SDWebUI\extensions\facechain\facechain\train_text_to_image_lora.py", line 829, in main
    raise ValueError(
ValueError: --caption_column' value 'text' needs to be one of: image
Error executing the command: Command '['python', 'C:\\SDWebUI\\extensions\\facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=C:\\SDWebUI\\extensions\\facechain\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\person11', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=C:\\SDWebUI\\extensions\\facechain\\worker_data\\qw\\ly261666/cv_portrait_model\\person11', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\SDWebUI\extensions\facechain\app.py", line 147, in train_lora_fn
    subprocess.run(command, check=True)
  File "C:\Program Files\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'C:\\SDWebUI\\extensions\\facechain/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=C:\\SDWebUI\\extensions\\facechain\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\person11', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=C:\\SDWebUI\\extensions\\facechain\\worker_data\\qw\\ly261666/cv_portrait_model\\person11', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SDWebUI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\SDWebUI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\SDWebUI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\SDWebUI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\SDWebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\SDWebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\SDWebUI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\SDWebUI\extensions\facechain\app.py", line 801, in run
    train_lora_fn(base_model_path=base_model_path,
  File "C:\SDWebUI\extensions\facechain\app.py", line 150, in train_lora_fn
    raise gr.Error("训练失败 (Training failed)")
gradio.exceptions.Error: '训练失败 (Training failed)'

**Comment by frankea** [comment]
Same issue here, in reviewing the error and code, I've narrowed down these details (note: i'm a tester not a coder):

1. The script allows for specifying` --image_column` and `--caption_column`. If not specified, it defaults to the first and second columns of the dataset, respectively.
2. The script checks if the provided values for `--image_column` and `--caption_column` are present in `column_names`. If they are not, it raises a `ValueError`.
3. `column_names = dataset["train"].column_names` retrieves the column names of the training dataset. This means the script expects the dataset to have a specific structure with named columns.
4. The error we are encountering (`ValueError: --caption_column' value 'text' needs to be one of: image`) is due to `caption_column` not matching any of the column names in our dataset.
5. This suggests that either the dataset does not have a column named "text", or there is a discrepancy in how the dataset's columns are named or structured.

This is my first time ever looking at this code, so I'll keep digging.  I believe the solution will be one of the following:

1. **Verify Dataset Columns**: Ensure that the dataset's structure matches what the script expects. The first column should be the image data (or a reference to it), and the second should be the captions if we are using the default settings.
2. **Correct Argument Values**: If our dataset has different column names, we need to provide the correct column names using --image_column and --caption_column when running the script.
3. **Modify Dataset or Script (if necessary)**: If we cannot alter the dataset, we might need to modify the script to accommodate our dataset's structure.

To do that, I'll have to figure out how to:

1. **Inspect the Dataset**: Check the actual column names in the dataset.
2. **Adjust Command Arguments**: If our dataset's caption column is not named "text", adjust the --caption_column argument to match the actual column name.

Now to figure out exactly how to do either of those things.

**Comment by frankea** [comment]
**Issue Summary:**
Encountering a critical issue in a text-to-image model training script where the dataset structure does not match the expected format. The script anticipates a dataset with both `image `and `text `columns, but the loaded dataset contains only `image`. Based on my interpretation of the code, I assume that the dataset structure should mirror the `metadata.jsonl` file, which includes both image file names and their corresponding text descriptions.

**Details:**

1. **Dataset Structure Mismatch:** The primary issue is the absence of the `text `column in the dataset. This is evidenced by the error` ####FRANKEADEBUG#### Caption column 'text' not found in dataset columns: ['image']`. It suggests that the dataset preparation phase, governed by `Blipv2()` and related functions, does not include caption data as anticipated.
2. **Dataset Loading and Processing Output:** Debugging output confirms that the dataset only includes images. For instance, entries like:
> ####FRANKEADEBUG#### Entry 0: {'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=512x512 at 0x253AE4CA410>}
> ####FRANKEADEBUG#### Entry 1: {'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=512x512 at 0x253AE4CA3E0>}
> ####FRANKEADEBUG#### Entry 2: {'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=512x512 at 0x253AE46E9B0>}
showcase only image data without accompanying text.
3. **Discrepancy in Data Processing:** The `Blipv2()` class seems to correctly process images and generate tags (e.g., `####FRANKEADEBUG#### Image: 001.jpg, Tags: 1girl, blue_eyes, lips...`). However, these tags do not translate into the expected `text` column in the dataset. Instead, the dataset creation outputs JSON lines like `{"file_name": "0.png", "text": "<fcsks>, a beautiful woman"}`, which don't reflect the processed tags.
4. **Error Messages:** The script fails with a consistent theme of errors related to the missing `text` column. The repeated message  `####FRANKEADEBUG#### Caption column 'text' not found in dataset columns: ['image']` across different stages of script execution pinpoints the core issue.

**Recommendations for Resolution:**

1. **Dataset Creation Review:** Thoroughly review the dataset creation logic, particularly in the `Blipv2()` class. Focus should be on ensuring that it correctly associates the generated tags with their respective images in the `metadata.jsonl` file.
2. **Script Modification:** Modify the script to ensure that both image and text data are correctly processed and included in the dataset. This might involve changes in how the `metadata.jsonl` file is written.
5. **Enhanced Debugging:** Implement additional debugging print statements or checks at key stages of the dataset preparation and loading process. This would help validate each step and ensure the correct structure of the dataset.
6. **Manual Dataset Inspection:** After implementing changes, manually inspect the resulting `metadata.jsonl` file and dataset structure to confirm that they align with the expected format of having both image and text data.

Resolving this issue will require ensuring the dataset is structured correctly with both images and their corresponding text captions and that the script is capable of processing this data as intended.  That all said, it's late and this is the first time I'm looking at or using this code, so I could be way off.  I'll check some more stuff tomorrow unless someone happens to just fix it while I'm sleeping.

**Comment by frankea** [comment]
Progress has been made.  The problem is with the version of datasets.  I did a `pip install datasets==2.5.0 --force` followed by a `pip install fsspec==2023.9.2 --force` and it appears the issue has been resolved.

For next steps, I'll need to iterate through the versions of datasets to see what version the problem appears in.

**Comment by zanghyu** [comment]
`pip install fsspec==2023.9.2` followed by a `pip install modelscope==1.9.5` will solve the issue (modelscope-1.9.5 depends on datasets-2.13.0, and it could work).

**Comment by splitbot-tadeusz** [comment]
> `pip install fsspec==2023.9.2` followed by a `pip install modelscope==1.9.5` will solve the issue (modelscope-1.9.5 depends on datasets-2.13.0, and it could work).

Thanks @zanghyu. The two instructions solve the problem in my enviroment.

**Comment by mzxhzhp** [comment]
奇怪，无论我使用：
pip install modelscope==1.9.5
pip install fsspec==2023.9.2
还是：
pip install fsspec==2023.9.2 --force
pip install datasets==2.5.0 --force
结果还是不行。百思不得其解。

**Comment by mzxhzhp** [comment]
> 奇怪，无论我使用： pip install modelscope==1.9.5 pip install fsspec==2023.9.2 还是： pip install fsspec==2023.9.2 --force pip install datasets==2.5.0 --force 结果还是不行。百思不得其解。

我知道怎么解决了，将 dataset 改成 dataset = load_dataset("imagefolder", data_dir=args.dataset_name) 就可以了

**Comment by wangxingjun778** [comment]
fix, refer to latest version:  https://github.com/modelscope/facechain
