### ISSUE TITLE
ValueError: --caption_column' value 'text' needs to be one of: image

### ISSUE THREAD

**Issue by dengxuankun** [modelscope/facechain#513]
这个问题看有人提过并且解决了，但是我还是遇到了
cathed for image process of 000.jpg
Error: FIND was unable to find an engine to execute this computation
[]
Error: result is empty.
None
instance_data_dir /u02/big_model/facechain-main/worker_data/qw/training_data/ly261666/cv_portrait_model/gaoxing
** project dir: /u02/big_model/facechain-main
** params: >base_model_path:ly261666/cv_portrait_model, >revision:v2.0, >sub_path:film/film, >output_img_dir:/u02/big_model/facechain-main/worker_data/qw/training_data/ly261666/cv_portrait_model/gaoxing, >work_dir:/u02/big_model/facechain-main/worker_data/qw/ly261666/cv_portrait_model/gaoxing, >lora_r:4, >lora_alpha:32
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2024-02-06 16:34:35,097 - modelscope - INFO - PyTorch version 2.0.0+cu118 Found.
2024-02-06 16:34:35,099 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-02-06 16:34:35,126 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 eafe6b806ea361850ec791d6490c1eaf and a total number of 946 components indexed
/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/accelerate/accelerator.py:393: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
02/06/2024 16:34:36 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

2024-02-06 16:34:36,586 - modelscope - INFO - Use user-specified model revision: v2.0
{'clip_sample_range', 'dynamic_thresholding_ratio', 'variance_type', 'thresholding', 'rescale_betas_zero_snr', 'sample_max_value'} was not found in config. Values will be initialized to default values.
/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
{'force_upcast'} was not found in config. Values will be initialized to default values.
{'reverse_transformer_layers_per_block', 'dropout', 'attention_type'} was not found in config. Values will be initialized to default values.
Generating train split: 1 examples [00:00, 165.23 examples/s]
Traceback (most recent call last):
  File "/u02/big_model/facechain-main/facechain/train_text_to_image_lora.py", line 1224, in <module>
    main()
  File "/u02/big_model/facechain-main/facechain/train_text_to_image_lora.py", line 831, in main
    raise ValueError(
ValueError: --caption_column' value 'text' needs to be one of: image
Traceback (most recent call last):
  File "/root/anaconda3/envs/torch2.0.0py38/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/torch2.0.0py38/bin/python', '/u02/big_model/facechain-main/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=/u02/big_model/facechain-main/worker_data/qw/training_data/ly261666/cv_portrait_model/gaoxing', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=/u02/big_model/facechain-main/worker_data/qw/ly261666/cv_portrait_model/gaoxing', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/anaconda3/envs/torch2.0.0py38/lib/python3.8/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 804, in run
    train_lora_fn(base_model_path=base_model_path,
  File "app.py", line 207, in train_lora_fn
    raise gr.Error("训练失败 (Training failed)")
gradio.exceptions.Error: '训练失败 (Training failed)'

**Comment by sunbaigui** [comment]
please try out the newest train-free, 10s inference version facechain-fact.
