### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by xupeng19881010** [modelscope/facechain#564]
女巫风(Witch style)
2024-06-16 23:16:06,070 - modelscope - INFO - Use user-specified model revision: v1.0.0
绿野仙踪(Wizard of Oz)
2024-06-16 23:16:06,489 - modelscope - INFO - Use user-specified model revision: v1.0.0
藏族风(ZangZu Style)
2024-06-16 23:16:07,034 - modelscope - INFO - Use user-specified model revision: v1.0.0
壮族服装风(Zhuang style)
2024-06-16 23:16:07,547 - modelscope - INFO - Use user-specified model revision: v5
盔甲风(Armor)
芭比娃娃(Barbie Doll)
2024-06-16 23:16:08,017 - modelscope - INFO - Use user-specified model revision: v2
休闲生活风(Casual Lifestyle)
2024-06-16 23:16:08,635 - modelscope - INFO - Use user-specified model revision: v2
凤冠霞帔(Chinese traditional gorgeous suit)
2024-06-16 23:16:09,079 - modelscope - INFO - Use user-specified model revision: v1.0.0
赛博朋克(Cybernetics punk)
优雅公主(Elegant Princess)
2024-06-16 23:16:09,493 - modelscope - INFO - Use user-specified model revision: v2
女士晚礼服(Gown)
汉服风(Hanfu)
白月光(Innocent Girl in White Dress)
鬼马少女(Pixy Girl)
2024-06-16 23:16:09,904 - modelscope - INFO - Use user-specified model revision: v2
白雪公主(Snow White)
2024-06-16 23:16:10,444 - modelscope - INFO - Use user-specified model revision: v1.0.0
T恤衫(T-shirt)
工作服(Working suit)
2024-06-16 23:16:10,887 - modelscope - INFO - Use user-specified model revision: v1.0.1
2024-06-16 23:16:12,083 - modelscope - INFO - Use user-specified model revision: v1.0.1
*** Error executing callback ui_tabs_callback for G:\backup\novelai-webui-aki-v3\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\utils\import_utils.py", line 451, in _get_module
        return importlib.import_module('.' + module_name, self.__name__)
      File "D:\Soft\python\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\models\cv\image_human_parsing\m2fp_net.py", line 13, in <module>
        from modelscope.models.cv.image_instance_segmentation.maskdino_swin import \
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\models\cv\image_instance_segmentation\maskdino_swin.py", line 16, in <module>
        from .maskdino.maskdino_decoder import MaskDINODecoder
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\models\cv\image_instance_segmentation\maskdino\maskdino_decoder.py", line 9, in <module>
        from .dino_decoder import DeformableTransformerDecoderLayer, TransformerDecoder
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\models\cv\image_instance_segmentation\maskdino\dino_decoder.py", line 10, in <module>
        from .ms_deform_attn import MSDeformAttn
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\models\cv\image_instance_segmentation\maskdino\ms_deform_attn.py", line 20, in <module>
        from mmcv.ops.multi_scale_deform_attn import (
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\mmcv\ops\__init__.py", line 10, in <module>
        from .carafe import CARAFE, CARAFENaive, CARAFEPack, carafe, carafe_naive
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\mmcv\ops\carafe.py", line 11, in <module>
        from ..cnn import UPSAMPLE_LAYERS, normal_init, xavier_init
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\mmcv\cnn\__init__.py", line 14, in <module>
        from .builder import MODELS, build_model_from_cfg
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\mmcv\cnn\builder.py", line 2, in <module>
        from ..runner import Sequential
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\mmcv\runner\__init__.py", line 45, in <module>
        from mmcv.device import ipu  # isort:skip  # noqa
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\mmcv\device\__init__.py", line 2, in <module>
        from . import ipu, mlu, mps, npu
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\mmcv\device\npu\__init__.py", line 3, in <module>
        from .data_parallel import NPUDataParallel
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\mmcv\device\npu\data_parallel.py", line 20, in <module>
        for m in sys.modules:
    RuntimeError: dictionary changed size during iteration

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "G:\backup\novelai-webui-aki-v3\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "G:\backup\novelai-webui-aki-v3\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "G:\backup\novelai-webui-aki-v3\extensions\facechain\app.py", line 434, in <module>
        gen_portrait = GenPortrait()
      File "G:\backup\novelai-webui-aki-v3\extensions\facechain\facechain\inference_fact.py", line 292, in __init__
        self.segmentation_pipeline = pipeline(
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
        return build_pipeline(cfg, task_name=task)
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
        return build_from_cfg(
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\utils\registry.py", line 184, in build_from_cfg
        LazyImportModule.import_module(sig)
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\utils\import_utils.py", line 475, in import_module
        importlib.import_module(module_name)
      File "D:\Soft\python\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\pipelines\cv\image_human_parsing_pipeline.py", line 9, in <module>
        from modelscope.models.cv.image_human_parsing import (
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\utils\import_utils.py", line 434, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "G:\backup\novelai-webui-aki-v3\venv\lib\site-packages\modelscope\utils\import_utils.py", line 453, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import modelscope.models.cv.image_human_parsing.m2fp_net because of the following error (look up to see its traceback):
    dictionary changed size during iteration

---

**Comment by You-Cun** [comment]
It seems that the environment is not installed correctly. It is recommended to follow our installation guide.
