### ISSUE TITLE
mmcv-full在2.0.0版本后更名为mmcv了

### ISSUE THREAD

**Issue by didoll-john** [modelscope/facechain#566]
mmcv-full更名为mmcv
mmcv更名为mmcv-lite
代码中依然要求安装mmcv-full，一直报错。
ERROR:  Failed building wheel for mmcv-full

**Comment by didoll-john** [comment]
或者能否指定一下mmcv-full的版本？我尝试了1.7.2，也报错

**Comment by xupeng19881010** [comment]
mmcv-full边缘不成功，是你vs和cuda编译环境有问题

**Comment by didoll-john** [comment]
我对Windows确实不熟悉，目前环境是Windows 11，CUDA版本12.5，vs 2022安装了并勾选了使用C++的桌面开发，还有什么需要安装或者注意的吗？
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:36:51_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0



      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
          subprocess.run(
        File "subprocess.py", line 571, in run
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '19']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Deca\AppData\Local\Temp\pip-install-m2fs9fhn\mmcv-full_7688a3da137149abbc95308ecf255ea2\setup.py", line 543, in <module>
          setup(
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\build_ext.py", line 91, in run
          _build_ext.run(self)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 870, in build_extensions
          build_ext.build_extensions(self)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\command\build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\Cython\Distutils\build_ext.py", line 127, in build_extension
          super(build_ext, self).build_extension(ext)
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 842, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects`

**Comment by sunbaigui** [comment]
merged to #516 .Try to establish the CPU-only pipeline to reduce issues that may arise when using GPUs across different platforms.
