### ISSUE TITLE
Windows 11 - No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by 3dgonzalog** [modelscope/facechain#572]
Can't seem to get the right version of MMCV to work for this project on Windows 11. Anyone got it to work?

Error: 
ModuleNotFoundError: DamoFdDetect: No module named 'mmcv._ext'

Current version of mmcv

Name: mmcv
Version: 1.7.1
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Contributors
Author-email: openmmlab@gmail.com
License:
Location: c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages
Requires: addict, numpy, opencv-python, packaging, Pillow, pyyaml, regex, yapf
Required-by:

Full log:

2024-06-22 18:32:36,008 - modelscope - INFO - PyTorch version 2.0.0+cu118 Found.
2024-06-22 18:32:36,010 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2024-06-22 18:32:36,184 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 028fc15f95751ef77d01ff4983f006b9 and a total number of 946 components indexed
C:\Users\Administrator\Desktop\facechain-3.0.0\app.py:1276: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\1.jpg'], ['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\2.jpg'], ['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\3.jpg'], ['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\4.jpg'], ['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\5.jpg']]
[['resources/tryon_garment\\garment1.png'], ['resources/tryon_garment\\garment2.png'], ['resources/tryon_garment\\garment3.png'], ['resources/tryon_garment\\garment4.png']]
Running on local URL:  http://127.0.0.1:7860
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
Running on public URL: https://78fb2a6f054069e315.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
显存足够
** Setting base model to SD1.5 **
--------uuid:  qw
----------work_dir:  C:\Users\Administrator\Desktop\facechain-3.0.0\worker_data\qw\ly261666/cv_portrait_model\person111435gdff
2024-06-22 18:32:54,339 - modelscope - INFO - Use user-specified model revision: v1.0.0
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
2024-06-22 18:32:58,845 - modelscope - INFO - PyTorch version 2.0.0+cu118 Found.
2024-06-22 18:32:58,847 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2024-06-22 18:32:58,952 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 028fc15f95751ef77d01ff4983f006b9 and a total number of 946 components indexed
C:\Users\Administrator\Desktop\facechain-3.0.0\app.py:1276: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  output_images = gr.Gallery(label='Output', show_label=False).style(columns=3, rows=2, height=600,
[['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\1.jpg'], ['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\2.jpg'], ['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\3.jpg'], ['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\4.jpg'], ['C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/resources/inpaint_template\\5.jpg']]
[['resources/tryon_garment\\garment1.png'], ['resources/tryon_garment\\garment2.png'], ['resources/tryon_garment\\garment3.png'], ['resources/tryon_garment\\garment4.png']]
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
2024-06-22 18:33:03,586 - modelscope - INFO - Use user-specified model revision: v4.0
2024-06-22 18:33:06,734 - modelscope - INFO - Use user-specified model revision: v1.0.1
2024-06-22 18:33:07,263 - modelscope - WARNING - ('PIPELINES', 'skin-retouching-torch', 'skin-retouching-torch') not found in ast index file
2024-06-22 18:33:07,263 - modelscope - INFO - initiate model from C:\Users\Administrator\.cache\modelscope\hub\damo\cv_unet_skin_retouching_torch
2024-06-22 18:33:07,264 - modelscope - INFO - initiate model from location C:\Users\Administrator\.cache\modelscope\hub\damo\cv_unet_skin_retouching_torch.
2024-06-22 18:33:07,269 - modelscope - WARNING - No preprocessor field found in cfg.
2024-06-22 18:33:07,269 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-06-22 18:33:07,270 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\Administrator\\.cache\\modelscope\\hub\\damo\\cv_unet_skin_retouching_torch'}. trying to build by task and model information.
2024-06-22 18:33:07,270 - modelscope - WARNING - Find task: skin-retouching-torch, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2024-06-22 18:33:10,326 - modelscope - WARNING - Model revision not specified, use revision: v2.0.2
2024-06-22 18:33:10,718 - modelscope - INFO - initiate model from C:\Users\Administrator\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
2024-06-22 18:33:10,719 - modelscope - INFO - initiate model from location C:\Users\Administrator\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
2024-06-22 18:33:10,725 - modelscope - WARNING - No preprocessor field found in cfg.
2024-06-22 18:33:10,725 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-06-22 18:33:10,725 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\Administrator\\.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2024-06-22 18:33:10,725 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2024-06-22 18:33:10,727 - modelscope - INFO - loading model from C:\Users\Administrator\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
2024-06-22 18:33:11,066 - modelscope - INFO - load model done
2024-06-22 18:33:11.7776266 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_4__1660'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:11.7802151 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'Shape__1662:0'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:11.7823610 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'Sub__1664:0'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1007753 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2649'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1033023 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2644'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1056388 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2647'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1081369 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2658'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1108493 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2648'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1131175 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2657'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1152813 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2653'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1174420 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2652'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1195884 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2645'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1217259 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2643'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1241771 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2641'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1264277 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2633'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1285767 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2632'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1306800 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2624'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1327419 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2614'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1348559 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2613'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1369087 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2606'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1393488 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2598'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1414744 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2596'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:12.1438304 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2594'. It is not used by any node and should be removed from the model.
2024-06-22 18:33:14,311 - modelscope - INFO - Use user-specified model revision: v1.1
2024-06-22 18:33:14,813 - modelscope - INFO - initiate model from C:\Users\Administrator\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd
2024-06-22 18:33:14,813 - modelscope - INFO - initiate model from location C:\Users\Administrator\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd.
2024-06-22 18:33:14,815 - modelscope - INFO - initialize model from C:\Users\Administrator\.cache\modelscope\hub\damo\cv_ddsar_face-detection_iclr23-damofd
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\models\base\base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\models\cv\face_detection\scrfd\damofd_detect.py", line 31, in __init__
    super().__init__(model_dir, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\models\cv\face_detection\scrfd\scrfd_detect.py", line 36, in __init__
    from mmdet.models import build_detector
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mmdet\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mmdet\models\backbones\__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mmdet\models\backbones\csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mmdet\models\utils\__init__.py", line 13, in <module>
    from .point_sample import (get_uncertain_point_coords_with_randomness,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mmdet\models\utils\point_sample.py", line 3, in <module>
    from mmcv.ops import point_sample
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\pipelines\cv\face_detection_pipeline.py", line 36, in __init__
    super().__init__(model=model, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\pipelines\base.py", line 99, in __init__
    self.model = self.initiate_single_model(model)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: DamoFdDetect: No module named 'mmcv._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\facechain-3.0.0\facechain\inference.py", line 25, in _data_process_fn_process
    Blipv2()(input_img_dir)
  File "C:\Users\Administrator\Desktop\facechain-3.0.0\facechain\data_process\preprocessing.py", line 207, in __init__
    self.face_detection = pipeline(task=Tasks.face_detection, model='damo/cv_ddsar_face-detection_iclr23-damofd', model_revision='v1.1')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: FaceDetectionPipeline: DamoFdDetect: No module named 'mmcv._ext'
instance_data_dir C:\Users\Administrator\Desktop\facechain-3.0.0\worker_data\qw\training_data\ly261666/cv_portrait_model\person111435gdff
2024-06-22 18:33:20,179 - modelscope - INFO - PyTorch version 2.0.0+cu118 Found.
2024-06-22 18:33:20,181 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2024-06-22 18:33:20,279 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 028fc15f95751ef77d01ff4983f006b9 and a total number of 946 components indexed
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py:401: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
06/22/2024 18:33:22 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

2024-06-22 18:33:23,628 - modelscope - INFO - Use user-specified model revision: v2.0
{'dynamic_thresholding_ratio', 'variance_type', 'clip_sample_range', 'sample_max_value', 'rescale_betas_zero_snr', 'thresholding'} was not found in config. Values will be initialized to default values.
{'force_upcast'} was not found in config. Values will be initialized to default values.
{'dropout', 'reverse_transformer_layers_per_block', 'attention_type'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\facechain-3.0.0\facechain\train_text_to_image_lora.py", line 1224, in <module>
    main()
  File "C:\Users\Administrator\Desktop\facechain-3.0.0\facechain\train_text_to_image_lora.py", line 789, in main
    dataset = load_dataset("imagefolder", data_dir=args.dataset_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\datasets\load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\datasets\load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\datasets\load.py", line 1768, in dataset_module_factory
    ).get_module()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\datasets\load.py", line 1133, in get_module
    patterns = sanitize_patterns(self.data_files) if self.data_files is not None else get_data_patterns(base_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\datasets\data_files.py", line 485, in get_data_patterns
    raise EmptyDatasetError(f"The directory at {base_path} doesn't contain any data files") from None
datasets.data_files.EmptyDatasetError: The directory at C:/Users/Administrator/Desktop/facechain-3.0.0/worker_data/qw/training_data/ly261666/cv_portrait_model/person111435gdff_labeled doesn't contain any data files
Error executing the command: Command '['python', 'C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=C:\\Users\\Administrator\\Desktop\\facechain-3.0.0\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\person111435gdff', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=C:\\Users\\Administrator\\Desktop\\facechain-3.0.0\\worker_data\\qw\\ly261666/cv_portrait_model\\person111435gdff', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\facechain-3.0.0\app.py", line 147, in train_lora_fn
    subprocess.run(command, check=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'C:\\Users\\Administrator\\Desktop\\facechain-3.0.0/facechain/train_text_to_image_lora.py', '--pretrained_model_name_or_path=ly261666/cv_portrait_model', '--revision=v2.0', '--sub_path=film/film', '--output_dataset_name=C:\\Users\\Administrator\\Desktop\\facechain-3.0.0\\worker_data\\qw\\training_data\\ly261666/cv_portrait_model\\person111435gdff', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=200', '--checkpointing_steps=5000', '--learning_rate=1.5e-04', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--seed=42', '--output_dir=C:\\Users\\Administrator\\Desktop\\facechain-3.0.0\\worker_data\\qw\\ly261666/cv_portrait_model\\person111435gdff', '--lora_r=4', '--lora_alpha=32', '--lora_text_encoder_r=32', '--lora_text_encoder_alpha=32', '--resume_from_checkpoint=fromfacecommon']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\facechain-3.0.0\app.py", line 804, in run
    train_lora_fn(base_model_path=base_model_path,
  File "C:\Users\Administrator\Desktop\facechain-3.0.0\app.py", line 150, in train_lora_fn
    raise gr.Error("训练失败 (Training failed)")
gradio.exceptions.Error: '训练失败 (Training failed)'

**Comment by nitinmukesh** [comment]
@3dgonzalog 
Please let me know how you install it on Windows. I tried both Auto1111 and standalone installation but nothing is working

**Comment by 3dgonzalog** [comment]
I ended up installing WSL on windows, then, everything works as expected because you are essentially running  a Linux VM on your windows machine :).

**Comment by nitinmukesh** [comment]
> I ended up installing WSL on windows, then, everything works as expected because you are essentially running a Linux VM on your windows machine :).

Thank for letting me know.
