### ISSUE TITLE
The tab doesn't work at all

### ISSUE THREAD

**Issue by GlukXP** [modelscope/facechain#593]
After installing through the available extensions, I did not find the "Facechain" tab. I tried different ways to launch/update/reinstall, including completely disabling third-party webui add-ons. didn't help. Explain: what am I doing wrong?

I found these lines in the window:

Creating model from config: I:\stable-diffusion-portable-main\configs\v1-inference.yaml
*** Error executing callback ui_tabs_callback for I:\stable-diffusion-portable-main\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "I:\stable-diffusion-portable-main\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "I:\stable-diffusion-portable-main\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "I:\stable-diffusion-portable-main\extensions\facechain\app.py", line 16, in <module>
        from facechain.inference_fact import GenPortrait
      File "I:\stable-diffusion-portable-main\extensions\facechain\facechain\inference_fact.py", line 10, in <module>
        from controlnet_aux import OpenposeDetector
      File "I:\stable-diffusion-portable-main\venv\lib\site-packages\controlnet_aux\__init__.py", line 11, in <module>
        from .mediapipe_face import MediapipeFaceDetector
      File "I:\stable-diffusion-portable-main\venv\lib\site-packages\controlnet_aux\mediapipe_face\__init__.py", line 9, in <module>
        from .mediapipe_face_common import generate_annotation
      File "I:\stable-diffusion-portable-main\venv\lib\site-packages\controlnet_aux\mediapipe_face\mediapipe_face_common.py", line 5, in <module>
        import mediapipe as mp
      File "I:\stable-diffusion-portable-main\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
        import mediapipe.python.solutions as solutions
      File "I:\stable-diffusion-portable-main\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
        import mediapipe.python.solutions.drawing_styles
      File "I:\stable-diffusion-portable-main\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 21, in <module>
        from mediapipe.python.solutions.hands import HandLandmark
      File "I:\stable-diffusion-portable-main\venv\lib\site-packages\mediapipe\python\solutions\hands.py", line 23, in <module>
        from mediapipe.calculators.core import constant_side_packet_calculator_pb2
      File "I:\stable-diffusion-portable-main\venv\lib\site-packages\mediapipe\calculators\core\constant_side_packet_calculator_pb2.py", line 31, in <module>
        mediapipe_dot_framework_dot_calculator__options__pb2.CalculatorOptions.RegisterExtension(_CONSTANTSIDEPACKETCALCULATOROPTIONS.extensions_by_name['ext'])
    AttributeError: type object 'CalculatorOptions' has no attribute 'RegisterExtension'

**Comment by spencerfrost** [comment]
Same here. Can't get it to work.

**Comment by sunbaigui** [comment]
The same issue as #577 ？

**Comment by GlukXP** [comment]
> The same issue as #577 ？

It looks like it, but no. I have Automatic1111 WebUI version: v1.10.1 and there seems to be another error in the window.

**Comment by sunbaigui** [comment]
merged to #577 as WebUI bug.
