### ISSUE TITLE
error on A1111 installing it on the latest version 1.10.1

### ISSUE THREAD

**Issue by elliotchav** [modelscope/facechain#612]
The extentions installation is fine, but when you try to apply and reload UI the extension breaks, showing these errors

```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Installing requirements
Installing requirements for diffusers
CUDA 12.1
Launching Web UI with arguments: --xformers
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.9.0, num models: 10
ControlNet preprocessor location: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-10-18 12:09:17,591 - ControlNet - INFO - ControlNet v1.1.455
12:09:18 - ReActor - STATUS - Running v0.7.1-b2 on Device: CPU
Loading weights [f327bf38a5] from C:\AI\stable-diffusion-webui\models\Stable-diffusion\_SDXL_1_0\🟡_STOIQO_NewReality_FLUX_SD_XL_Lightning\STOIQONewrealityFLUXSD_XLPRO.safetensors
2024-10-18 12:09:19,136 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: C:\AI\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
*** Error executing callback ui_tabs_callback for C:\AI\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\AI\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "C:\AI\stable-diffusion-webui\extensions\facechain\app.py", line 16, in <module>
        from facechain.inference_fact import GenPortrait
      File "C:\AI\stable-diffusion-webui\extensions\facechain\facechain\inference_fact.py", line 20, in <module>
        from modelscope.pipelines import pipeline
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
        from modelscope.msdatasets import MsDataset
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
        from modelscope.msdatasets.ms_dataset import MsDataset
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in <module>
        from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict
    ModuleNotFoundError: No module named 'datasets'

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
🤯 LobeTheme: Initializing...
Startup time: 41.8s (prepare environment: 21.8s, import torch: 7.4s, import gradio: 1.3s, setup paths: 1.2s, initialize shared: 0.2s, other imports: 0.7s, load scripts: 4.5s, create ui: 4.3s, gradio launch: 0.3s).
Applying attention optimization: xformers... done.
Model loaded in 16.3s (load weights from disk: 1.0s, create model: 1.0s, apply weights to model: 12.9s, apply half(): 0.2s, move model to device: 0.6s, calculate empty prompt: 0.5s).
```

**Comment by nitinmukesh** [comment]
> ModuleNotFoundError: No module named 'datasets'

activate virtual environment

pip install datasets

**Comment by elliotchav** [comment]
thank you

**Comment by elliotchav** [comment]
> > ModuleNotFoundError: No module named 'datasets'
> 
> activate virtual environment
> 
> pip install datasets

even after installing datasets this is the new error log:

```
Error executing callback ui_tabs_callback for C:\AI\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\AI\stable-diffusion-webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "C:\AI\stable-diffusion-webui\extensions\facechain\app.py", line 574, in <module>
        gen_portrait = GenPortrait()
      File "C:\AI\stable-diffusion-webui\extensions\facechain\facechain\inference_fact.py", line 292, in __init__
        self.segmentation_pipeline = pipeline(
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 130, in pipeline
        cfg = read_config(
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\hub.py", line 64, in read_config
        return Config.from_file(local_path)
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\config.py", line 132, in from_file
        cfg_dict, cfg_text = Config._file2dict(filename)
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\utils\config.py", line 117, in _file2dict
        cfg_dict = load(tmp_cfg_file.name)
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\fileio\io.py", line 48, in load
        obj = handler.load(f, **kwargs)
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\fileio\format\json.py", line 26, in load
        from . import jsonplus
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\modelscope\fileio\format\jsonplus.py", line 8, in <module>
        import simplejson as json
    ModuleNotFoundError: No module named 'simplejson'

---
Running on local URL:  http://127.0.0.1:7860

```

**Comment by You-Cun** [comment]
Please try to install datasets with version 2.16.0 or 3.0.2.

**Comment by sunbaigui** [comment]
merge to #623
