### ISSUE TITLE
Models failing to download

### ISSUE THREAD

**Issue by aleksandar-babic** [modelscope/facechain#623]
Hi,

I followed the instructions to run facechain in the docker container, and one of the files failed to download:

```
root@d70f88239db8:/facechain# python3 app.py
/opt/conda/lib/python3.8/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
[2024-10-31 05:26:57,991] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-10-31 05:26:58.379559: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
/opt/conda/lib/python3.8/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
2024-10-31 05:26:59,450 - modelscope - INFO - PyTorch version 2.0.1+cu117 Found.
2024-10-31 05:26:59,451 - modelscope - INFO - Loading ast index from /mnt/workspace/.cache/modelscope/ast_indexer
2024-10-31 05:26:59,502 - modelscope - INFO - No valid ast index found from /mnt/workspace/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2024-10-31 05:26:59,561 - modelscope - INFO - Loading done! Current index file version is 1.8.1, with md5 2c26b8f616d95476e0bf242e6c0cabb6 and a total number of 893 components indexed
秋日胡杨风(Autumn populus euphratica style)
2024-10-31 05:27:01,072 - modelscope - INFO - Use user-specified model revision: v1
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 111MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 113MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 91.7MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 721/721 [00:00<00:00, 88.4kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 89.3MB/s]
萧瑟秋天风(Bleak autumn style)
2024-10-31 05:27:13,838 - modelscope - INFO - Use user-specified model revision: v1
漫画风(Cartoon)
2024-10-31 05:27:14,684 - modelscope - INFO - Use user-specified model revision: v1.0.0
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.1M/72.1M [00:00<00:00, 106MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 136/136 [00:00<00:00, 16.5kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 589/589 [00:00<00:00, 489kB/s]
旗袍风(Cheongsam)
2024-10-31 05:27:19,293 - modelscope - INFO - Use user-specified model revision: v1.0.0
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120/120 [00:00<00:00, 92.7kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 111MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.1M/72.1M [00:00<00:00, 114MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.1M/36.1M [00:00<00:00, 102MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.1M/72.1M [00:00<00:00, 124MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 111MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.1M/36.1M [00:00<00:00, 104MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 113MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18.1M/18.1M [00:00<00:00, 64.4MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.1M/36.1M [00:00<00:00, 100MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.1M/72.1M [00:00<00:00, 102MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 95.9MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144M/144M [00:01<00:00, 88.9MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 599/599 [00:00<00:00, 73.3kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 142k/142k [00:00<00:00, 2.20MB/s]
中国新年风(Chinese New Year Style)
2024-10-31 05:27:50,738 - modelscope - INFO - Use user-specified model revision: v2
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.1M/36.1M [00:00<00:00, 89.8MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.1M/36.1M [00:00<00:00, 73.4MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.1M/36.1M [00:00<00:00, 73.3MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.1M/72.1M [00:00<00:00, 108MB/s]
Downloading: 72.1MB [00:03, 19.2MB/s]
2024-10-31 05:28:04,761 - modelscope - ERROR - File liuli2.safetensors download incomplete, content_length: None but the                     file downloaded length: 75615600, please download again
Retry 1/3: File liuli2.safetensors download incomplete, content_length: None but the                     file downloaded length: 75615600, please download again
2024-10-31 05:28:06,283 - modelscope - INFO - Use user-specified model revision: v2
Downloading: 72.1MB [00:01, 52.5MB/s]
2024-10-31 05:28:08,870 - modelscope - ERROR - File liuli2.safetensors download incomplete, content_length: None but the                     file downloaded length: 75615600, please download again
Retry 2/3: File liuli2.safetensors download incomplete, content_length: None but the                     file downloaded length: 75615600, please download again
2024-10-31 05:28:10,369 - modelscope - INFO - Use user-specified model revision: v2
Downloading: 72.1MB [00:01, 47.9MB/s]
2024-10-31 05:28:13,102 - modelscope - ERROR - File liuli2.safetensors download incomplete, content_length: None but the                     file downloaded length: 75615600, please download again
Retry 3/3: File liuli2.safetensors download incomplete, content_length: None but the                     file downloaded length: 75615600, please download again
Traceback (most recent call last):
  File "app.py", line 572, in <module>
    model_dir = snapshot_download(style['model_id'], revision=style['revision'])
  File "/facechain/facechain/utils.py", line 23, in wrapper
    raise Exception(f"Max retries ({max_attempts}) exceeded.")
Exception: Max retries (3) exceeded.
```

I used a non-ch docker image since I'm not based in china mainland.

Any ideas on how to get around this?

Thanks

**Comment by zengqixun12** [comment]
I have the same error..

`/opt/conda/lib/python3.8/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
[2024-10-31 10:43:04,777] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-10-31 10:43:05.075564: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
/opt/conda/lib/python3.8/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
2024-10-31 10:43:05,901 - modelscope - INFO - PyTorch version 2.0.1+cu117 Found.
2024-10-31 10:43:05,903 - modelscope - INFO - Loading ast index from /mnt/workspace/.cache/modelscope/ast_indexer
2024-10-31 10:43:05,925 - modelscope - INFO - Loading done! Current index file version is 1.8.1, with md5 2c26b8f616d95476e0bf242e6c0cabb6 and a total number of 893 components indexed
秋日胡杨风(Autumn populus euphratica style)
2024-10-31 10:43:06,677 - modelscope - INFO - Use user-specified model revision: v1
Downloading: 144MB [00:00, 237MB/s]  
2024-10-31 10:43:08,119 - modelscope - ERROR - File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
Retry 1/3: File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
2024-10-31 10:43:09,345 - modelscope - INFO - Use user-specified model revision: v1
Downloading: 144MB [00:00, 233MB/s] 
2024-10-31 10:43:10,753 - modelscope - ERROR - File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
Retry 2/3: File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
2024-10-31 10:43:12,073 - modelscope - INFO - Use user-specified model revision: v1
Downloading: 144MB [00:00, 239MB/s] 
2024-10-31 10:43:13,576 - modelscope - ERROR - File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
Retry 3/3: File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
Traceback (most recent call last):
  File "app.py", line 572, in <module>
    model_dir = snapshot_download(style['model_id'], revision=style['revision'])
  File "/mnt/workspace/facechain/facechain/utils.py", line 23, in wrapper
    raise Exception(f"Max retries ({max_attempts}) exceeded.")
Exception: Max retries (3) exceeded.`

**Comment by sunbaigui** [comment]
hi @You-Cun ,Please take a look at this when you get a chance.

**Comment by You-Cun** [comment]
Please run "pip install modelscope -U", then run "pip install datasets==2.16".

**Comment by CesarOqoCL** [comment]
> Please run "pip install modelscope -U", then run "pip install datasets==2.16".

i intall and i have the same error

**Comment by ouoertheo** [comment]
Running into similar issues as the referenced ticket, figured you were trying to consolidate here. I'm using the latest sd-web-ui

I installed `datasets 2.16.0`, which then required another dependency for `oss2`, which then required another dependency for `simplejson`, which is now requiring another dependency for `sortedcontainers`. 

I stopped about here because it's 2+ minutes to boot sd-web-ui with this extension installed, as it checks and downloads a bunch of resources. I've followed the dependency path down to where there's no more `module not found` errors previously, and it results in a broken install of facechain - ie. training does not work.

I've noticed that modelscope has some pretty complex dependencies when I checked out their repo requirements folder, and all these dependency failures seem to be spawning from modelscope.
