### ISSUE TITLE
can't download models in the ModelScope notebook !

### ISSUE THREAD

**Issue by zengqixun12** [modelscope/facechain#624]
I use 'ubuntu20.04-py38-torch2.0.1-tf1.15.5-modelscope1.8.1' 

and. run :
```

!GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/modelscope/facechain.git --depth 1

import os
os.chdir('/mnt/workspace/facechain')    # You may change to your own path
print(os.getcwd())

!pip3 install gradio==3.47.1
!pip3 install controlnet_aux==0.0.6
!pip3 install python-slugify
!pip3 install diffusers==0.29.0
!pip3 install peft==0.11.1

!python3 app.py
```

then in the python3 app.py step, error occured:

`root@dsw-713877-77d685988d-sgvx9:/mnt/workspace/facechain# python3 app.py 
/opt/conda/lib/python3.8/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
[2024-10-31 10:43:04,777] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-10-31 10:43:05.075564: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
/opt/conda/lib/python3.8/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
2024-10-31 10:43:05,901 - modelscope - INFO - PyTorch version 2.0.1+cu117 Found.
2024-10-31 10:43:05,903 - modelscope - INFO - Loading ast index from /mnt/workspace/.cache/modelscope/ast_indexer
2024-10-31 10:43:05,925 - modelscope - INFO - Loading done! Current index file version is 1.8.1, with md5 2c26b8f616d95476e0bf242e6c0cabb6 and a total number of 893 components indexed
秋日胡杨风(Autumn populus euphratica style)
2024-10-31 10:43:06,677 - modelscope - INFO - Use user-specified model revision: v1
Downloading: 144MB [00:00, 237MB/s]  
2024-10-31 10:43:08,119 - modelscope - ERROR - File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
Retry 1/3: File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
2024-10-31 10:43:09,345 - modelscope - INFO - Use user-specified model revision: v1
Downloading: 144MB [00:00, 233MB/s] 
2024-10-31 10:43:10,753 - modelscope - ERROR - File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
Retry 2/3: File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
2024-10-31 10:43:12,073 - modelscope - INFO - Use user-specified model revision: v1
Downloading: 144MB [00:00, 239MB/s] 
2024-10-31 10:43:13,576 - modelscope - ERROR - File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
Retry 3/3: File autumn_populus.safetensors download incomplete, content_length: None but the                     file downloaded length: 151112445, please download again
Traceback (most recent call last):
  File "app.py", line 572, in <module>
    model_dir = snapshot_download(style['model_id'], revision=style['revision'])
  File "/mnt/workspace/facechain/facechain/utils.py", line 23, in wrapper
    raise Exception(f"Max retries ({max_attempts}) exceeded.")
Exception: Max retries (3) exceeded.`

**Comment by sunbaigui** [comment]
hi @You-Cun ,Please take a look at this when you get a chance.

**Comment by You-Cun** [comment]
Please run "pip install modelscope -U", then run "pip install datasets==2.16".

**Comment by sunbaigui** [comment]
merge to #623
