### ISSUE TITLE
Errors on ForgeUI v1.10.1

### ISSUE THREAD

**Issue by madmax17** [modelscope/facechain#625]
No tab is shown

Error executing callback ui_tabs_callback for C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\extensions\facechain\app.py", line 16, in <module>        from facechain.inference_fact import GenPortrait
      File "C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\extensions\facechain\facechain\inference_fact.py", line 20, in <module>
        from modelscope.pipelines import pipeline
      File "C:\Users\madma\Documents\webui_forge_cu121_torch231\system\python\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "C:\Users\madma\Documents\webui_forge_cu121_torch231\system\python\lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
        from modelscope.msdatasets import MsDataset
      File "C:\Users\madma\Documents\webui_forge_cu121_torch231\system\python\lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
        from modelscope.msdatasets.ms_dataset import MsDataset
      File "C:\Users\madma\Documents\webui_forge_cu121_torch231\system\python\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in <module>
        from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict
    ModuleNotFoundError: No module named 'datasets'

**Comment by cschwarzhw** [comment]
Have identical issue

**Comment by heartbreakergaming** [comment]
+1

**Comment by sunbaigui** [comment]
hi @You-Cun , Please take a look at this when you get a chance.

**Comment by dot-mike** [comment]
This can be fixed by activating the venv and installing the packages needed:

assuming linux
```bash
source venv/bin/activate
python -m pip install -U oss2 datasets==2.18.0
```

**Comment by christopher-conley** [comment]
> No tab is shown
> 
> Error executing callback ui_tabs_callback for C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\extensions\facechain\scripts\facechain_sdwebui.py Traceback (most recent call last): File "C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback res += c.callback() or [] File "C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs import app File "C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\extensions\facechain\app.py", line 16, in from facechain.inference_fact import GenPortrait File "C:\Users\madma\Documents\webui_forge_cu121_torch231\webui\extensions\facechain\facechain\inference_fact.py", line 20, in from modelscope.pipelines import pipeline File "C:\Users\madma\Documents\webui_forge_cu121_torch231\system\python\lib\site-packages\modelscope\pipelines__init__.py", line 4, in from .base import Pipeline File "C:\Users\madma\Documents\webui_forge_cu121_torch231\system\python\lib\site-packages\modelscope\pipelines\base.py", line 16, in from modelscope.msdatasets import MsDataset File "C:\Users\madma\Documents\webui_forge_cu121_torch231\system\python\lib\site-packages\modelscope\msdatasets__init__.py", line 2, in from modelscope.msdatasets.ms_dataset import MsDataset File "C:\Users\madma\Documents\webui_forge_cu121_torch231\system\python\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 9, in from datasets import Dataset, DatasetDict, IterableDataset, IterableDatasetDict ModuleNotFoundError: No module named 'datasets'

You need to install a version of the `datasets` Python package below version 3.0.2, there's a bug in it.
`python3 -m pip install datasets==3.0.1`

I just went through this just an hour ago and this was the fix.

**Comment by sunbaigui** [comment]
merge to #623
