### ISSUE TITLE
Error: nms_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by ultimatech-cn** [modelscope/facechain#68]
When upload picture and start trainning, there will be error on server side.
`2023-08-19 16:09:33,371 - modelscope - INFO - load model done
cathed for image process of 000.jpg
Error: nms_impl: implementation for device cuda:0 not found.

[]
Error: result is empty.
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\fchain\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\fchain\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\fchain\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\fchain\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\fchain\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\fchain\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\fchain\lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "D:\dev\facechain\app.py", line 174, in run
    data_process_fn(instance_data_dir, True)
  File "D:\dev\facechain\facechain\inference.py", line 24, in data_process_fn
    out_json_name = data_process_fn(input_img_dir)
  File "D:\dev\facechain\facechain\data_process\preprocessing.py", line 335, in __call__
    exit()
  File "C:\ProgramData\anaconda3\envs\fchain\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None`

**Comment by ultimatech-cn** [comment]
resolve the issue myself 
```
mim uninstall mmcv-full==1.7.0
pip install mmcv-full
```

It will take twenty minutes to finish.

**Comment by shengzewen** [comment]
It didn't work, bro
