### ISSUE TITLE
使用自定义lora模型生成图片报错：'获取模型版本失败，信息：record not found'

### ISSUE THREAD

**Issue by FeyaM** [modelscope/facechain#96]
步骤：
1. 将包含lora模型`sweet_dress_style2_v1.safetensors`的文件夹`liblibai_sweet_dress_lora`放于`mnt/workspace/.cache/modelscope/ly261666`
2. 编辑`facechain/facechain/constants.py`文件：
```Python
neg_prompt = 'nsfw, paintings, sketches, (worst quality:2), (low quality:2) ' \
             'lowers, normal quality, ((monochrome)), ((grayscale)), logo, word, character'
pos_prompt_with_cloth = 'raw photo, masterpiece, chinese, simple background, wearing {}, high-class pure color background, solo, medium shot, high detail face, looking straight into the camera with shoulders parallel to the frame, slim body, photorealistic, best quality'
pos_prompt_with_style = '{} upper_body, raw photo, masterpiece, chinese, solo, medium shot, high detail face, slim body, photorealistic, best quality'


cloth_prompt = [
    {'name': '工作服(working suit)', 'prompt': 'high-class business/working suit'},  # male and female
    {'name': '盔甲风(armor)', 'prompt': 'silver armor'},  # male
    {'name': 'T恤衫(T-shirt)', 'prompt': 'T-shirt'},  # male and female
    {'name': '汉服风(hanfu)', 'prompt': 'beautiful traditional hanfu, upper_body'},  # female
    {'name': '女士晚礼服(gown)', 'prompt': 'an elegant evening gown'},  # female
    {'name': '洛丽塔(sweet lolita)', 'prompt':'sweet_dress,white thighhighs'}
]

styles = [
    {'name': '默认风格(default style)'},
    {'name': '凤冠霞帔(Chinese traditional gorgeous suit)',
     'model_id': 'ly261666/civitai_xiapei_lora',
     'revision': 'v1.0.0',
     'bin_file': 'xiapei.safetensors',
     'multiplier_style': 0.35,
     'cloth_name': '汉服风(hanfu)',
     'add_prompt_style': 'red, hanfu, tiara, crown, '},
    {'name': '甜美洛丽塔(sweet lolita)',
     'model_id': 'ly261666/liblibai_sweet_dress_lora',
     'revision': 'v1.0.0',
     'bin_file': 'sweet_dress_style2_v1.safetensors',
     'multiplier_style': 0.65,
     'cloth_name': '洛丽塔(lolita)',
     'add_prompt_style': 'sweet_dress,white thighhighs, amusement park, night, night sky, dramatic lighting,'},
]
```
3. 启动，生成默认图片成功
4. 调用`甜美洛丽塔`风格提示词报错，生成失败。报错：
```Bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1428, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1245, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/opt/conda/lib/python3.8/site-packages/gradio/components/radio.py", line 161, in preprocess
    return self.choices.index(x)
ValueError: '洛丽塔(lolita)' is not in list
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1428, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1245, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/opt/conda/lib/python3.8/site-packages/gradio/components/radio.py", line 161, in preprocess
    return self.choices.index(x)
ValueError: '洛丽塔(lolita)' is not in list
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1428, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1245, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/opt/conda/lib/python3.8/site-packages/gradio/components/radio.py", line 161, in preprocess
    return self.choices.index(x)
ValueError: '洛丽塔(lolita)' is not in list
2023-08-22 15:51:01,471 - modelscope - ERROR - Authentication token does not exist, failed to access model ly261666/liblibai_sweet_dress_lora which may not exist or may be                 private. Please login first.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/modelscope/hub/errors.py", line 81, in handle_http_response
    response.raise_for_status()
  File "/opt/conda/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://www.modelscope.cn/api/v1/models/ly261666/liblibai_sweet_dress_lora/revisions?EndTime=1692690661

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 349, in async_iteration
    return await iterator.__anext__()
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 342, in __anext__
    return await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 325, in run_sync_iterator_async
    return next(iterator)
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 694, in gen_wrapper
    yield from f(*args, **kwargs)
  File "app.py", line 109, in launch_pipeline
    model_dir = snapshot_download(matched['model_id'], revision=matched['revision'])
  File "/opt/conda/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 96, in snapshot_download
    revision = _api.get_valid_revision(
  File "/opt/conda/lib/python3.8/site-packages/modelscope/hub/api.py", line 479, in get_valid_revision
    revisions = self.list_model_revisions(
  File "/opt/conda/lib/python3.8/site-packages/modelscope/hub/api.py", line 433, in list_model_revisions
    handle_http_response(r, logger, cookies, model_id)
  File "/opt/conda/lib/python3.8/site-packages/modelscope/hub/errors.py", line 88, in handle_http_response
    raise HTTPError('Response details: %s' % message) from error
requests.exceptions.HTTPError: Response details: {'Code': 10010205001, 'Message': '获取模型版本失败，信息：record not found', 'RequestId': '6a8d9e85-80ac-46b9-9572-e6fc4746a5b4', 'Success': False}
```
ps：建议将资源文件从缓存目录移到项目文件夹下，方便开发者们开发

**Comment by sunbaigui** [comment]
欢迎报名开发更多风格，我们会有专项答疑，后续也会录制相应教程。如有兴趣共建开发更多风格commit到该开源项目，可以发送联系方式到sunbaigui85@126.com
